"""Render the ESA origin-protection whitelist as an Nginx real-IP snippet.

Usage: aliyun esa GetOriginProtection --region cn-hangzhou --SiteId <id> \
         | python3 deploy/esa_origin_ips.py nginx > /etc/nginx/snippets/esa-origin-ips.conf
       ... | python3 deploy/esa_origin_ips.py ipv4   (one CIDR per line, for the ECS prefix list)
Uses the union of CurrentIPWhitelist and the not-yet-confirmed LatestIPWhitelist, so new ranges can be
allowed at the origin before they are confirmed in ESA. Rerun after confirming to drop removed ranges.
"""
import ipaddress
import json
import sys

mode = sys.argv[1] if len(sys.argv) > 1 else 'nginx'
data = json.load(sys.stdin)
lists = [data.get('CurrentIPWhitelist') or {}, data.get('LatestIPWhitelist') or {}]
ipv4 = sorted({str(ipaddress.ip_network(c)) for l in lists for c in l.get('IPv4') or []})
ipv6 = sorted({str(ipaddress.ip_network(c)) for l in lists for c in l.get('IPv6') or []})
if not ipv4:
    sys.exit('empty ESA origin whitelist')
if mode == 'ipv4':
    print('\n'.join(ipv4))
elif mode == 'nginx':
    print('# Generated by deploy/esa_origin_ips.py from the ESA origin whitelist. Do not edit by hand.')
    for cidr in ipv4 + ipv6:
        print(f'set_real_ip_from {cidr};')
    print('real_ip_header ali-real-client-ip;')
else:
    sys.exit('mode must be nginx or ipv4')
