import { useEffect, useRef, useState } from 'react'
import { Plus, Pencil, Eye, Upload, Check } from 'lucide-react'
import { api, patch } from '../lib/api'
import { prepareUploadImage } from '../lib/image'
import { previewUrl } from '../lib/preview'
import { searchMatcher } from '../lib/search'
import type { Sticker } from '../lib/types'
import { Empty, Modal, Spinner, TEMPLATE_CATEGORIES, useNotice } from '../components/UI'
import { ImagePreview } from '../components/ImagePreview'

export function StickerChooser({stickers,value,onChange}:{stickers:Sticker[];value:string[];onChange:(ids:string[])=>void}) {
 const [search,setSearch]=useState(''),[category,setCategory]=useState('all')
 const matches=searchMatcher(search)
 const filtered=stickers.filter(s=>(s.active||value.includes(s.id))&&(category==='all'||category===s.category)&&matches(s.code+' '+s.name))
 return <><div className="filter-bar"><label className="search-input"><input aria-label="搜索贴纸" value={search} placeholder="搜索贴纸编号或名称" onChange={e=>setSearch(e.target.value)}/></label><select aria-label="筛选贴纸分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部分类</option>{TEMPLATE_CATEGORIES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div><div className="template-picker">{filtered.map(s=><button type="button" key={s.id} className={'template-option '+(value.includes(s.id)?'selected':'')} disabled={!s.active&&!value.includes(s.id)} aria-pressed={value.includes(s.id)} onClick={()=>onChange(value.includes(s.id)?value.filter(id=>id!==s.id):[...value,s.id])}><img className="avatar" src={previewUrl(s.image.url)} alt=""/><div><strong>{s.name}</strong><span>{s.code}{!s.active?' · 已停用':''}</span></div>{value.includes(s.id)?<Check size={16}/>:<Plus size={16}/>}</button>)}</div>{!filtered.length&&<Empty title="没有匹配的贴纸" description="调整分类或搜索条件。"/>}</>
}
function StickerEditor({sticker,onClose,onSaved}:{sticker:Sticker|null;onClose:()=>void;onSaved:()=>void}) {
 const [code,setCode]=useState(sticker?.code||''),[name,setName]=useState(sticker?.name||''),[category,setCategory]=useState(sticker?.category||'boy'),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false)
 const notice=useNotice(),controller=useRef<AbortController|null>(null)
 useEffect(()=>()=>controller.current?.abort(),[])
 async function save(){if(controller.current)return;const c=new AbortController();controller.current=c;setBusy(true);try{const form=new FormData();if(sticker){form.append('code',code);form.append('name',name);form.append('category',category)}else{form.append('codes',JSON.stringify(files.map(f=>f.name.replace(/\.[^.]+$/,''))))}
 for(const file of files)form.append(sticker?'file':'files',await prepareUploadImage(file,c.signal));await api(sticker?'/stickers/'+sticker.id:'/stickers',{method:sticker?'PUT':'POST',body:form,signal:c.signal});if(!c.signal.aborted){notice(sticker?'贴纸已更新，旧订单保留原版本':'贴纸已上传');onSaved();onClose()}}catch(e){if(!c.signal.aborted)notice((e as Error).message,'error')}finally{controller.current=null;setBusy(false)}}
 return <Modal title={sticker?'编辑贴纸':'批量上传贴纸'} onClose={onClose}><fieldset className="template-edit-fields" disabled={busy}>{sticker&&<><label className="field">贴纸编号<input value={code} onChange={e=>setCode(e.target.value)}/></label><label className="field">贴纸名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">分类<select value={category} onChange={e=>setCategory(e.target.value)}>{TEMPLATE_CATEGORIES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><ImagePreview src={sticker.image.url} alt={sticker.name}/></>}<label className="upload-template button"><Upload size={16}/>{sticker?'替换图片（可选）':'选择贴纸图片'}<input type="file" multiple={!sticker} accept="image/png,image/jpeg,image/webp" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{!sticker&&<p className="hint">文件名去掉扩展名作为贴纸编号；编号必须唯一。上传后可编辑名称和分类。</p>}<ul>{files.map((f,i)=><li key={i}>{f.name}{!sticker?' → '+f.name.replace(/\.[^.]+$/,''):''}</li>)}</ul></fieldset><div className="modal-footer"><button className="button primary" disabled={busy||(sticker?!code.trim()||!name.trim():!files.length)} onClick={()=>void save()}>{busy&&<Spinner/>}保存贴纸</button></div></Modal>
}
export function Stickers({stickers,canEdit,onRefresh}:{stickers:Sticker[];canEdit:boolean;onRefresh:()=>void}) {
 const [editor,setEditor]=useState<Sticker|null|undefined>(),[preview,setPreview]=useState<Sticker|null>(null),[search,setSearch]=useState(''),[category,setCategory]=useState('all');const notice=useNotice(),matches=searchMatcher(search)
 const filtered=stickers.filter(s=>(category==='all'||s.category===category)&&matches(s.code+' '+s.name))
 return <><div className="page-heading"><div><h1>贴纸库</h1><p>公共贴纸统一维护，可单张选择，也可组合成模板套装。</p></div>{canEdit&&<button className="button primary" onClick={()=>setEditor(null)}><Plus size={16}/>批量上传</button>}</div><div className="filter-bar"><label className="search-input"><input aria-label="搜索贴纸" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索编号或名称"/></label><select aria-label="贴纸分类" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">全部分类</option>{TEMPLATE_CATEGORIES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div><div className="template-library">{filtered.map(s=><article className="library-set" key={s.id}><button className="library-mosaic sticker-cover" onClick={()=>setPreview(s)} aria-label={'预览 '+s.name}><img src={previewUrl(s.image.url)} alt={s.name} loading="lazy"/></button><div className="library-details"><div><h3>{s.name}</h3><p>{s.code} · v{s.revision}</p></div><span className={'availability '+(s.active?'on':'')}>{s.active?'已启用':'已停用'}</span></div><div className="library-actions"><button className="text-button" onClick={()=>setPreview(s)}><Eye size={15}/>预览</button>{canEdit&&s.editable&&<><button className="text-button" onClick={()=>setEditor(s)}><Pencil size={15}/>编辑</button><button className="text-button" onClick={async()=>{try{await patch('/stickers/'+s.id,{active:!s.active});onRefresh()}catch(e){notice((e as Error).message,'error')}}}>{s.active?'停用':'启用'}</button></>}</div></article>)}</div>{!filtered.length&&<Empty title="暂无匹配的贴纸" description="公共贴纸上传后会显示在这里。"/>}{canEdit&&editor!==undefined&&<StickerEditor sticker={editor} onClose={()=>setEditor(undefined)} onSaved={onRefresh}/>} {preview&&<Modal title={preview.code+' · '+preview.name} onClose={()=>setPreview(null)}><ImagePreview src={preview.image.url} alt={preview.name}/></Modal>}</>
}
