import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {uploadStickers} from './library-fixtures'
import {createCustomer,pixel,staffLogin} from './customer-fixtures'

test('picker 已选 tab lists this avatar\'s templates and stickers with editable quantities',async({page})=>{
  await staffLogin(page.request)
  const suffix=randomUUID().slice(0,6).toUpperCase()
  const stickers=await uploadStickers(page.request,[0,1,2,3].map(i=>({name:`SEL${suffix}-${i}.png`,mimeType:'image/png',buffer:pixel})))
  const set=await page.request.post('/api/templates',{data:{code:`SELSET-${suffix}`,name:'已选套装',category:'general',sticker_ids:stickers.slice(2).map(s=>s.id)}});expect(set.ok(),await set.text()).toBeTruthy()
  const order=await createCustomer(page.request,{generation_limit:10,final_count:1})
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.setViewportSize({width:390,height:844})
  await page.goto('/guest')
  await page.getByLabel('订单号',{exact:true}).fill(order.order_number);await page.getByRole('button',{name:'进入订单'}).click()
  await page.getByLabel('上传头像').setInputFiles({name:'a.png',mimeType:'image/png',buffer:pixel})
  await page.getByRole('button',{name:'选择模板和贴纸'}).click()
  const picker=page.getByRole('dialog',{name:'选择模板和贴纸'})
  const selectedTab=picker.getByRole('button',{name:/^已选 \d+$/})
  await expect(selectedTab).toHaveText('已选 0')
  await selectedTab.click();await expect(picker.getByText('还没有选择')).toBeVisible()
  await picker.getByRole('button',{name:'单张贴纸',exact:true}).click()
  await picker.getByLabel('搜索模板或贴纸').fill(suffix)
  await picker.getByLabel(stickers[0].code+' 份数',{exact:true}).fill('2')
  await picker.getByLabel(stickers[1].code+' 份数',{exact:true}).fill('1')
  await picker.getByRole('button',{name:'模板套装',exact:true}).click()
  await picker.getByLabel(`SELSET-${suffix} 份数`,{exact:true}).fill('1')
  await expect(selectedTab).toHaveText('已选 5')
  await selectedTab.click()
  await expect(selectedTab).toHaveClass(/active/)
  const sets=picker.getByRole('region',{name:'已选模板套装'}),singles=picker.getByRole('region',{name:'已选单张贴纸'})
  await expect(sets.locator('article')).toHaveCount(1);await expect(singles.locator('article')).toHaveCount(2)
  await expect(singles.getByLabel(stickers[0].code+' 份数',{exact:true})).toHaveValue('2')
  await page.evaluate(()=>Promise.allSettled(document.getAnimations().map(animation=>animation.finished)))
  await page.screenshot({path:'test-results/picker-selected-390.png'})
  // Reducing to 0 keeps the card in place so it can be added back.
  await singles.getByRole('button',{name:stickers[1].code+' 减少份数',exact:true}).click()
  await expect(singles.locator('article')).toHaveCount(2);await expect(singles.getByLabel(stickers[1].code+' 份数',{exact:true})).toHaveValue('0')
  await expect(selectedTab).toHaveText('已选 4')
  await singles.getByRole('button',{name:stickers[1].code+' 增加份数',exact:true}).click();await expect(selectedTab).toHaveText('已选 5')
  await singles.getByRole('button',{name:stickers[1].code+' 减少份数',exact:true}).click()
  // Re-opening drops cards at 0; search narrows the selected list too.
  await picker.getByRole('button',{name:'单张贴纸',exact:true}).click();await selectedTab.click()
  await expect(singles.locator('article')).toHaveCount(1)
  await picker.getByLabel('搜索模板或贴纸').fill(stickers[0].code)
  await expect(sets).toHaveCount(0);await expect(singles.locator('article')).toHaveCount(1)
  // The footer count jumps to 已选 from anywhere in the catalog.
  await picker.getByLabel('搜索模板或贴纸').fill(suffix)
  await picker.getByRole('button',{name:'单张贴纸',exact:true}).click()
  await picker.getByRole('button',{name:'本头像 4 张',exact:true}).click()
  await expect(selectedTab).toHaveClass(/active/);await expect(sets.locator('article')).toHaveCount(1)
  await picker.getByRole('button',{name:'应用选择'}).click()
  await expect(page.locator('.customer-avatar-name')).toContainText('4 张已选')
  expect(errors).toEqual([])
})
