import { test, expect } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { uploadStickers } from './library-fixtures'
import { completedCustomer, createCustomer, installDirectoryPicker, mutate, pixel, staffLogin } from './customer-fixtures'

test('staff opens order; guest uploads two avatars, repeats choices, compares rerun, selects finals and submits safely',async({page,browser})=>{
  await staffLogin(page.request)
  const stickers=await uploadStickers(page.request,[{name:'GUEST-A.png',mimeType:'image/png',buffer:pixel},{name:'GUEST-B.png',mimeType:'image/png',buffer:pixel}])
  const template=await page.request.post('/api/templates',{data:{code:'GUEST-SET',name:'客户测试套装',category:'general',sticker_ids:stickers.map(s=>s.id)}});expect(template.ok()).toBe(true)
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',message=>{if(['error','warning'].includes(message.type()))errors.push(message.text())})
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'客户订单',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'选择保存目录'})).toHaveCount(0)
  await page.getByRole('button',{name:'开新订单'}).click()
  const create=page.getByRole('dialog',{name:'开新订单'})
  const number='Guest-'+randomUUID().slice(0,8)
  await create.getByLabel('订单号',{exact:true}).fill(number)
  await create.getByLabel('可选图片上限').fill('4');await create.getByLabel('最终成品数量').fill('2');await create.getByLabel('每张可重跑次数').fill('1')
  await create.getByLabel('内部备注').fill('仅员工可见的备注')
  await create.getByRole('button',{name:'创建订单',exact:true}).click()
  await expect(page.getByRole('heading',{name:'订单 '+number})).toBeVisible()
  const order=(await(await page.request.get('/api/customer-orders')).json()).find((o:any)=>o.order_number===number)
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5174',viewport:{width:1440,height:1000}})
  try{
    const guest=await context.newPage();guest.on('pageerror',e=>errors.push(e.message));guest.on('console',message=>{if(['error','warning'].includes(message.type())&&!message.text().includes('401 (Unauthorized)'))errors.push(message.text())})
    const requests:string[]=[];guest.on('request',request=>requests.push(request.url()))
    await guest.goto('/guest');await expect(guest).toHaveURL(/\/guest$/);await expect(guest).toHaveTitle(/头像贴纸/);await expect(guest.locator('vite-error-overlay')).toHaveCount(0);await guest.getByLabel('订单号',{exact:true}).fill(number);await guest.getByRole('button',{name:'进入订单'}).click()
    await expect(guest.getByRole('heading',{name:'订单 '+number})).toBeVisible()
    await expect(guest.getByRole('navigation')).toHaveCount(0);await expect(guest.getByText('仅员工可见的备注')).toHaveCount(0)
    await guest.getByLabel('上传头像').setInputFiles([{name:'头像一.png',mimeType:'image/png',buffer:pixel},{name:'头像二.png',mimeType:'image/png',buffer:pixel}])
    await expect(guest.locator('.customer-avatar-row')).toHaveCount(2)
    await guest.getByRole('button',{name:'选择模板和贴纸'}).first().click()
    let picker=guest.getByRole('dialog',{name:'选择模板和贴纸'})
    await picker.getByLabel('搜索模板或贴纸').fill('GUEST-SET');await picker.getByLabel('GUEST-SET 份数').fill('1');await picker.getByRole('button',{name:'应用选择'}).click()
    await guest.getByRole('button',{name:'选择模板和贴纸'}).nth(1).click();picker=guest.getByRole('dialog',{name:'选择模板和贴纸'})
    await picker.getByRole('button',{name:'单张贴纸',exact:true}).click();await picker.getByLabel('搜索模板或贴纸').fill('GUEST-A');await picker.getByLabel('GUEST-A 份数').fill('2');await picker.getByRole('button',{name:'应用选择'}).click()
    await expect(guest.locator('.customer-submit-bar')).toContainText('已选 4 张')
    await guest.getByRole('button',{name:'核对并开始生成'}).click()
    const preflight=guest.getByRole('dialog',{name:'生成前核对'})
    await expect(preflight.locator('.customer-counts strong')).toHaveText(['2','4','3'])
    await preflight.getByRole('button',{name:'确认开始生成'}).click()
    await expect(guest.locator('.customer-result')).toHaveCount(4)
    await expect(guest.locator('.customer-result-image img')).toHaveCount(4,{timeout:60000})
    const detail=await(await page.request.get('/api/customer-orders/'+order.id)).json()
    expect(detail.slots[2].selected_version_id).toBe(detail.slots[3].selected_version_id)
    await guest.getByRole('button',{name:'查看 / 重跑'}).nth(2).click()
    const comparison=guest.getByRole('dialog',{name:'GUEST-A · 版本对比'})
    await comparison.getByRole('button',{name:'重新生成这一张'}).click();await comparison.getByRole('button',{name:'确认重跑这一张'}).click()
    await expect(comparison.locator('.customer-versions figure')).toHaveCount(2,{timeout:60000})
    await expect(guest.getByRole('button',{name:'确认成品并提交'})).toBeDisabled()
    await comparison.getByRole('button',{name:'保留旧版本'}).click()
    await expect(comparison.getByRole('button',{name:'已保留'})).toBeVisible()
    await comparison.getByRole('button',{name:'关闭',exact:true}).last().click()
    await guest.getByLabel('选择成品 3',{exact:true}).check();await guest.getByLabel('选择成品 1',{exact:true}).check()
    await expect(guest.locator('.customer-print-order')).toHaveCount(0)
    await expect(guest.getByText(/第 \d+ 张打印/)).toHaveCount(0)
    const submission=guest.waitForRequest(request=>request.url().endsWith('/api/guest/order/submit')&&request.method()==='POST')
    await guest.screenshot({path:'/tmp/avatar-studio-fal-qa/customer-review-desktop.png',fullPage:true})
    await guest.setViewportSize({width:390,height:844});expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await guest.screenshot({path:'/tmp/avatar-studio-fal-qa/customer-review-mobile.png',fullPage:true})
    await guest.getByRole('button',{name:'确认成品并提交'}).click();await guest.getByRole('dialog',{name:'确认最终成品'}).getByRole('button',{name:'确认提交',exact:true}).click()
    expect((await submission).postDataJSON().slot_ids).toEqual([detail.slots[0].id,detail.slots[2].id])
    await expect(guest.getByRole('heading',{name:'已提交印刷'})).toBeVisible();await expect(guest.locator('.customer-result')).toHaveCount(0)
    await expect(guest.getByAltText('已确认贴纸水印总览')).toBeVisible({timeout:60000})
    const safe=await(await guest.request.get('/api/guest/order')).json();expect(safe.slots).toBeUndefined();expect(safe.avatars).toBeUndefined();expect(safe.notes).toBeUndefined()
    expect(await guest.evaluate(()=>localStorage.length)).toBe(0)
    expect(requests.some(url=>/\/api\/(auth|customer-orders|orders|admin|account|assets)\//.test(url))).toBe(false)
    expect(requests.some(url=>/\/(App|device|delivery|db)\.(tsx?|js)/.test(url))).toBe(false)
    expect(requests.some(url=>url.includes(number))).toBe(false)
    await expect(guest.locator('a[download]')).toHaveCount(0)
  }finally{await context.close()}
  expect(errors).toEqual([])
})

test('guest cancellation polling closes previews and clears stale media, then restores',async({page,browser})=>{
  await staffLogin(page.request)
  const stickers=await(await page.request.get('/api/stickers')).json()
  let order=await completedCustomer(page.request,stickers[0].id,{order_number:'CANCEL-'+randomUUID().slice(0,8)})
  order=await mutate(page.request,order,'unlock')
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5174'})
  try{
    const guest=await context.newPage();await guest.request.post('/api/guest/login',{data:{order_number:order.order_number}});await guest.goto('/guest')
    await guest.getByRole('button',{name:'查看 / 重跑'}).click();await expect(guest.getByRole('dialog')).toBeVisible()
    const oldUrl=(await(await guest.request.get('/api/guest/order')).json()).slots[0].versions[0].preview_url
    order=await mutate(page.request,order,'cancel')
    await expect(guest.getByRole('heading',{name:'订单已取消'})).toBeVisible({timeout:10000})
    await expect(guest.getByRole('dialog')).toHaveCount(0);await expect(guest.locator('.customer-workbench img')).toHaveCount(0)
    expect((await guest.request.get(oldUrl)).status()).toBeGreaterThanOrEqual(400)
    await mutate(page.request,order,'restore')
    await expect(guest.getByRole('button',{name:'查看 / 重跑'})).toBeVisible({timeout:10000})
  }finally{await context.close()}
})

test('manual bulk print download selects one root, verifies hashes, preserves foreign files and supports ZIP',async({page})=>{
  await staffLogin(page.request)
  const sticker=(await(await page.request.get('/api/stickers')).json())[0]
  const orders=[await completedCustomer(page.request,sticker.id,{order_number:'PRINT-'+randomUUID().slice(0,8),notes:'客户/备注'}),await completedCustomer(page.request,sticker.id,{order_number:'PRINT-'+randomUUID().slice(0,8),notes:''})]
  await installDirectoryPicker(page)
  await page.goto('/');await expect(page.getByRole('heading',{name:'客户订单',exact:true})).toBeVisible()
  await page.waitForTimeout(300)
  expect(await page.evaluate(()=>(window as any).pickerCalls)).toBe(0)
  for(const order of orders)await page.getByLabel('选择订单 '+order.order_number,{exact:true}).check()
  await page.getByRole('button',{name:'批量下载打印文件 (2)',exact:true}).click()
  await expect(page.getByText('打印文件已保存',{exact:true})).toHaveCount(2)
  expect(await page.evaluate(()=>(window as any).pickerCalls)).toBe(1)
  const expected=await Promise.all(orders.map(async(order)=>{const manifest=await(await page.request.get('/api/customer-orders/'+order.id+'/manifest')).json();expect(manifest.files.every((file:any)=>file.kind==='print')).toBe(true);return manifest}))
  const saved=await page.evaluate(async()=>{const root=await(await navigator.storage.getDirectory()).getDirectoryHandle('manual-print-output');const found:Record<string,string[]>={};for await(const [name,directory] of root.entries()){found[name]=[];for await(const filename of (directory as FileSystemDirectoryHandle).keys())found[name].push(filename)}return found})
  expect(Object.keys(saved).sort()).toEqual(expected.map(m=>m.name).sort())
  for(const manifest of expected)expect(saved[manifest.name].sort()).toEqual(manifest.files.map((f:any)=>f.path).sort())
  await page.evaluate(()=>{(window as any).pickerCancel=true})
  await page.getByRole('button',{name:'批量下载打印文件 (2)',exact:true}).click();await expect(page.getByRole('button',{name:'批量下载打印文件 (2)',exact:true})).toBeEnabled()
  // A newly chosen root with foreign bytes must remain untouched.
  await page.evaluate(async manifest=>{
    const state=window as any;state.pickerCancel=false;state.pickerName='foreign-print-output'
    const directory=await(await(await navigator.storage.getDirectory()).getDirectoryHandle('foreign-print-output',{create:true})).getDirectoryHandle(manifest.name,{create:true})
    const writable=await(await directory.getFileHandle(manifest.files[0].path,{create:true})).createWritable();await writable.write('foreign-file');await writable.close()
  },expected[0])
  const first=page.locator('.customer-order-row').filter({hasText:orders[0].order_number})
  await first.getByRole('button',{name:'下载打印文件',exact:true}).click()
  await expect(first).toContainText('发现同名或被修改的文件')
  expect(await page.evaluate(async manifest=>{const directory=await(await(await navigator.storage.getDirectory()).getDirectoryHandle('foreign-print-output')).getDirectoryHandle(manifest.name);return(await(await directory.getFileHandle(manifest.files[0].path)).getFile()).text()},expected[0])).toBe('foreign-file')
  await page.evaluate(()=>{delete (window as any).showDirectoryPicker})
  await page.getByRole('button',{name:'批量下载打印文件 (2)',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'下载打印文件 ZIP'}).locator('a[download]')).toHaveCount(2)
})

test('active guest draft refreshes protected avatar and catalog URLs after batch watermark update',async({page,browser})=>{
  await staffLogin(page.request)
  const order=await createCustomer(page.request,{order_number:'WATERMARK-'+randomUUID().slice(0,8)})
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5174'})
  try{
    const guest=await context.newPage();await guest.request.post('/api/guest/login',{data:{order_number:order.order_number}});await guest.goto('/guest')
    await guest.getByLabel('上传头像').setInputFiles({name:'水印头像.png',mimeType:'image/png',buffer:pixel})
    const avatar=guest.locator('.customer-avatar-row img');await expect(avatar).toBeVisible()
    const before=await avatar.getAttribute('src')
    await guest.getByRole('button',{name:'选择模板和贴纸'}).click();await guest.getByRole('dialog').getByRole('button',{name:'单张贴纸',exact:true}).click()
    const image=guest.getByRole('dialog').locator('.customer-catalog img').first();await expect(image).toBeVisible();const previousCatalog=await image.getAttribute('src')
    await page.request.patch('/api/account',{data:{watermark:'新水印核对'}})
    await page.goto('/');await page.getByLabel('选择订单 '+order.order_number,{exact:true}).check();await page.getByRole('button',{name:'批量更新水印'}).click()
    const modal=page.getByRole('dialog',{name:'核对批量水印更新'});await expect(modal).toContainText('新水印核对');await modal.getByRole('button',{name:'确认更新 1 个订单'}).click();await expect(modal).toHaveCount(0)
    await expect(image).not.toHaveAttribute('src',previousCatalog!,{timeout:10000})
    await guest.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click()
    await expect(avatar).not.toHaveAttribute('src',before!,{timeout:10000})
    await expect.poll(()=>avatar.evaluate((img:HTMLImageElement)=>img.complete&&img.naturalWidth>0)).toBe(true)
    expect((await guest.request.get(before!)).status()).toBeGreaterThanOrEqual(400)
  }finally{await context.close()}
})

test('platform-only organization management creates administrator and limits organization navigation',async({page,browser})=>{
  await staffLogin(page.request)
  await page.goto('/');await page.getByRole('navigation').getByRole('button',{name:'组织管理',exact:true}).click()
  await page.getByRole('button',{name:'创建组织',exact:true}).click()
  const form=page.getByRole('dialog',{name:'创建组织'}),username='org'+randomUUID().slice(0,8)
  await form.getByLabel('组织名称').fill('浏览器验收组织');await form.getByLabel('管理员账号').fill(username);await form.getByLabel('管理员显示名称').fill('组织管理员')
  await form.getByRole('button',{name:'创建组织和管理员'}).click()
  const secret=page.getByRole('dialog',{name:'组织已创建'});await expect(secret.locator('code')).not.toBeEmpty();const password=await secret.locator('code').innerText()
  await secret.getByRole('button',{name:'已保存，关闭'}).click()
  const row=page.locator('.accounts-table tbody tr').filter({hasText:'浏览器验收组织'})
  await row.getByRole('button',{name:'修改名称'}).click();await page.getByRole('dialog').getByLabel('组织名称').fill('已改名验收组织');await page.getByRole('dialog').getByRole('button',{name:'保存名称'}).click()
  await expect(page.locator('.accounts-table tbody')).toContainText('已改名验收组织')
  const context=await browser.newContext({baseURL:'http://127.0.0.1:5174'})
  try{
    const admin=await context.newPage();expect((await admin.request.post('/api/auth/login',{data:{username,password}})).ok()).toBe(true);await admin.goto('/')
    await expect(admin.getByRole('heading',{name:'客户订单',exact:true})).toBeVisible()
    await expect(admin.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true})).toBeVisible()
    for(const label of ['组织管理','管理设置','全站统计'])await expect(admin.getByRole('navigation').getByRole('button',{name:label,exact:true})).toHaveCount(0)
    const renamed=page.locator('.accounts-table tbody tr').filter({hasText:'已改名验收组织'})
    await renamed.getByRole('button',{name:'停用组织'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认停用'}).click()
    expect((await admin.request.get('/api/auth/me')).status()).toBe(401)
    await renamed.getByRole('button',{name:'启用组织'}).click();await page.getByRole('dialog').getByRole('button',{name:'确认启用'}).click()
    expect((await admin.request.post('/api/auth/login',{data:{username,password}})).ok()).toBe(true)
  }finally{await context.close()}
})

test('independent superadmin starts in organization management without organization API reads',async({page})=>{
  const user=await staffLogin(page.request),requests:string[]=[]
  const independent={...user,role:'superadmin',organization_id:null,organization_name:null}
  await page.route('**/api/auth/status',route=>route.fulfill({json:{needs_setup:false,user:independent}}))
  await page.route('**/api/auth/me',route=>route.fulfill({json:independent}))
  page.on('request',request=>requests.push(new URL(request.url()).pathname))
  await page.goto('/');await expect(page.getByRole('heading',{name:'组织管理',exact:true,level:1})).toBeVisible()
  for(const name of ['工作台','贴纸库','模板库','历史订单'])await expect(page.getByRole('navigation').getByRole('button',{name,exact:true})).toHaveCount(0)
  expect(requests.some(path=>['/api/templates','/api/stickers','/api/orders','/api/customer-orders','/api/library/categories'].includes(path))).toBe(false)
})

test('staff reconciles applied-but-lost generate and rerun responses, then manages the full lifecycle',async({page})=>{
  await staffLogin(page.request)
  const sticker=(await(await page.request.get('/api/stickers')).json())[0]
  const order=await createCustomer(page.request,{order_number:'STAFF-'+randomUUID().slice(0,8)})
  await page.goto('/');await page.getByLabel('订单号',{exact:true}).fill(order.order_number)
  await page.getByRole('button',{name:'进入 / 代操作',exact:true}).click()
  await page.getByLabel('上传头像').setInputFiles({name:'员工代传.png',mimeType:'image/png',buffer:pixel})
  await page.getByRole('button',{name:'选择模板和贴纸'}).click()
  const picker=page.getByRole('dialog',{name:'选择模板和贴纸'})
  await picker.getByRole('button',{name:'单张贴纸',exact:true}).click();await picker.getByLabel('搜索模板或贴纸').fill(sticker.code);await picker.getByLabel(sticker.code+' 份数').fill('1');await picker.getByRole('button',{name:'应用选择'}).click()
  await page.getByRole('button',{name:'核对并开始生成'}).click()
  const payloads:unknown[]=[]
  await page.route('**/api/customer-orders/'+order.id+'/generate',async route=>{payloads.push(route.request().postDataJSON());if(payloads.length===1){const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed')}else await route.continue()})
  const confirm=page.getByRole('dialog',{name:'生成前核对'})
  await confirm.getByRole('button',{name:'确认开始生成'}).click();await expect(confirm.getByRole('button',{name:'返回调整'})).toBeEnabled()
  await confirm.getByRole('button',{name:'返回调整'}).click()
  await expect(page.locator('.customer-result-image img')).toHaveCount(1,{timeout:60000})
  await page.getByRole('button',{name:'重试确认上一操作',exact:true}).click()
  await expect(page.locator('.customer-pending-mutation')).toHaveCount(0)
  expect(payloads).toHaveLength(2);expect(payloads[0]).toEqual(payloads[1])
  const rerunPayloads:unknown[]=[]
  await page.route('**/api/customer-orders/'+order.id+'/slots/*/rerun',async route=>{rerunPayloads.push(route.request().postDataJSON());if(rerunPayloads.length===1){const response=await route.fetch();expect(response.ok()).toBe(true);await route.abort('failed')}else await route.continue()})
  await page.getByRole('button',{name:'查看 / 重跑'}).click()
  const comparison=page.getByRole('dialog')
  await comparison.getByRole('button',{name:'重新生成这一张'}).click();await comparison.getByRole('button',{name:'确认重跑这一张'}).click()
  await expect(comparison.locator('.customer-versions figure')).toHaveCount(2,{timeout:60000})
  await comparison.getByRole('button',{name:'重试确认上一操作',exact:true}).click()
  await expect(page.locator('.customer-pending-mutation')).toHaveCount(0)
  await comparison.getByRole('button',{name:'保留旧版本'}).click()
  await expect(comparison.getByRole('button',{name:'已保留'})).toBeVisible()
  await comparison.getByRole('button',{name:'关闭',exact:true}).last().click()
  expect(rerunPayloads).toHaveLength(2);expect(rerunPayloads[0]).toEqual(rerunPayloads[1])
  await page.getByLabel('选择成品 1',{exact:true}).check();await page.getByRole('button',{name:'确认成品并提交'}).click();await page.getByRole('dialog',{name:'确认最终成品'}).getByRole('button',{name:'确认提交',exact:true}).click()
  await expect(page.getByRole('heading',{name:'已提交印刷'})).toBeVisible()
  await page.getByRole('button',{name:'解锁选图'}).click();await page.getByRole('dialog',{name:'解锁订单'}).getByRole('button',{name:'确认解锁'}).click()
  await expect(page.getByLabel('选择成品 1',{exact:true})).toBeEnabled()
  await page.getByLabel('选择成品 1',{exact:true}).check();await page.getByRole('button',{name:'确认成品并提交'}).click();await page.getByRole('dialog',{name:'确认最终成品'}).getByRole('button',{name:'确认提交',exact:true}).click()
  await expect(page.getByRole('heading',{name:'已提交印刷'})).toBeVisible()
  await page.getByRole('button',{name:'重新排版',exact:true}).click();await page.getByRole('dialog',{name:'重新排版'}).getByLabel('单张内容长边').fill('50');await page.getByRole('dialog',{name:'重新排版'}).getByRole('button',{name:'确认排版'}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button',{name:'取消订单',exact:true}).click();await page.getByRole('dialog',{name:'取消订单'}).getByRole('button',{name:'确认取消'}).click()
  await expect(page.getByRole('heading',{name:'订单已取消'})).toBeVisible()
  await page.getByRole('button',{name:'返回订单'}).click()
  await page.getByLabel('订单状态').selectOption('cancelled');await expect(page.locator('.customer-order-row')).toHaveCount(1)
  await page.getByLabel('开始日期').fill('2099-01-01');await expect(page.locator('.customer-order-row')).toHaveCount(0);await page.getByLabel('开始日期').fill('')
  await page.getByRole('button',{name:'恢复订单'}).click();await page.getByRole('dialog',{name:'恢复订单'}).getByRole('button',{name:'确认恢复'}).click();await expect(page.locator('.customer-order-row')).toHaveCount(0)
  await page.getByLabel('订单状态').selectOption('submitted');await expect(page.locator('.customer-order-row')).toHaveCount(1)
})
