import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

const evidence = (name:string) => join(tmpdir(), 'avatar-studio-fal-qa', name)

// Small opaque input is intentional: the injected provider supplies transparent output.
const pixel = readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
const files = Array.from({ length: 12 }, (_, i) => ({ name: `template-${i+1}.png`, mimeType: 'image/png', buffer: pixel }))

async function installDirectoryPicker(page:Page,name='e2e-output') {
  await page.addInitScript(name=>{
    const state=window as Window & {pickerName?:string;openedDirectory?:string;pickerCalls?:number;pickerCancel?:boolean}
    window.showDirectoryPicker=async options=>{
      if(options?.mode==='read'&&options.startIn&&typeof options.startIn!=='string'){
        state.openedDirectory=options.startIn.name
        return options.startIn as FileSystemDirectoryHandle
      }
      state.pickerCalls=(state.pickerCalls||0)+1
      if(state.pickerCancel)throw new DOMException('Cancelled','AbortError')
      if(!state.pickerName&&options?.startIn&&typeof options.startIn!=='string')return options.startIn as FileSystemDirectoryHandle
      const chosen=state.pickerName||name
      return (await navigator.storage.getDirectory()).getDirectoryHandle(chosen,{create:true})
    }
  },name)
}

test('complete production UI workflow with isolated provider and data', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message=>{if(message.type()==='error')errors.push(message.text())})
  await installDirectoryPicker(page)
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '创建管理员账号' })).toBeVisible()
  await page.getByLabel('显示名称', { exact: true }).fill('联调管理员')
  await page.getByLabel('账号', { exact: true }).fill('testadmin')
  await page.locator('input[name=password]').fill('local-test-password')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await expect(page.getByRole('heading', { name: '批量制作' })).toBeVisible()
  await page.getByRole('navigation').getByRole('button', { name: '管理设置' }).click()
  await expect(page.getByLabel('FAL API Key')).toHaveAttribute('type', 'password')
  await expect(page.getByLabel('每分钟最多发起的生图请求')).toHaveCount(0)
  await expect(page.getByLabel('最大同时处理数量')).toHaveAttribute('max', '40')
  await page.getByRole('navigation').getByRole('button', { name: '工作台', exact: true }).click()
  await page.screenshot({ path: evidence('workspace-empty.png'), fullPage: true })

  await page.getByRole('navigation').getByRole('button', { name: '模板库' }).click()
  await page.getByRole('button', { name: '新建套装' }).first().click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('套装编号').pressSequentially('B001')
  await expect(dialog.getByLabel('套装编号')).toHaveValue('B001')
  await dialog.getByLabel('套装名称').pressSequentially('春日出游')
  await expect(dialog.getByLabel('套装名称')).toHaveValue('春日出游')
  await dialog.locator('input[type=file]').setInputFiles(files)
  await dialog.getByRole('button', { name: '保存套装' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '春日出游' })).toBeVisible()
  await expect(page.locator('.library-mosaic img').first()).toHaveAttribute('src', /\/preview\?size=320$/)

  await page.getByRole('navigation').getByRole('button', { name: '工作台', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles([{ name: '小满.png', mimeType: 'image/png', buffer: pixel }, { name: '岁岁.png', mimeType: 'image/png', buffer: pixel }])
  await expect(page.getByLabel('订单名称')).toHaveCount(2)
  await expect(page.getByText('图片名称／保存文件夹名',{exact:true})).toHaveCount(2)
  await expect(page.getByRole('button',{name:'提交生成'})).toBeDisabled()
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  await expect(page.locator('.directory-button')).toHaveText('e2e-output')
  await page.getByLabel('订单名称').nth(1).fill('岁岁成品')
  await page.evaluate(()=>{(window as Window & {pickerName?:string}).pickerName='e2e-custom'})
  await page.getByTitle('单独选择此订单的保存位置').nth(1).click()
  await expect(page.getByTitle('单独选择此订单的保存位置').nth(1)).toHaveText('e2e-custom')
  await page.evaluate(()=>{(window as Window & {pickerName?:string}).pickerName='e2e-output'})

  await page.getByRole('button', { name: '批量选择模板' }).click()
  await dialog.getByLabel('搜索模板套装').fill('b001')
  await expect(dialog.getByRole('button', { name: /春日出游/ })).toBeVisible()
  await dialog.getByRole('button', { name: /春日出游/ }).click()
  await dialog.getByLabel('搜索模板套装').fill('不存在的模板')
  await expect(dialog.getByText('没有匹配的模板套装')).toBeVisible()
  await expect(dialog.getByText('已选 1 套 · 12 张')).toBeVisible()
  await dialog.getByLabel('搜索模板套装').fill(' 春日 ')
  await expect(dialog.locator('.template-option.selected')).toHaveCount(1)

  await dialog.getByRole('button', { name: '应用到 2 个订单' }).click()
  await page.getByRole('button', { name: '打印参数', exact: true }).click()
  await dialog.getByLabel('单张内容长边').fill('50')
  await dialog.getByRole('button', { name: '保存参数' }).click()
  await expect(page.getByText('预计生成')).toBeVisible()
  await expect(page.locator('.print-summary').first()).toContainText('5 cm')
  await expect(page.getByText('草稿已保存',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('订单名称')).toHaveCount(2)
  await expect(page.locator('.print-summary').first()).toContainText('5 cm')
  await page.screenshot({ path: evidence('workspace-orders.png'), fullPage: true })
  await page.getByRole('button', { name: '提交生成' }).click()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button', { name: '任务中心' }).click()
  await expect(page.getByRole('heading', { name: '小满', exact: true })).toBeVisible()
  await expect.poll(async () => (await page.request.get('/api/orders')).json().then(rows => rows.every((o: { status: string }) => o.status === 'completed')), { timeout: 40000 }).toBe(true)
  const orders = await (await page.request.get('/api/orders')).json()
  const order = orders.find((o: { name: string }) => o.name === '小满')
  await page.getByRole('button', { name: /小满.*B001/ }).click()
  await expect(page.locator('.artifact')).toHaveCount(2)
  await expect(page.getByText('已保存到本机', { exact: true })).toBeVisible()
  // New global choices cannot redirect either submitted order.
  await page.evaluate(()=>{(window as Window & {pickerName?:string}).pickerName='e2e-other'})
  await page.locator('.directory-button').click()
  await expect(page.locator('.directory-button')).toHaveText('e2e-other')
  await page.evaluate(()=>{delete (window as Window & {pickerName?:string}).pickerName})

  await page.getByRole('button', { name: '单张结果' }).click()
  await page.locator('.result-card').first().click()
  await expect(dialog.getByRole('heading')).toHaveText('B001 · 第 1 张')
  await page.screenshot({path:evidence('result-review.png'),animations:'disabled'})
  await dialog.getByRole('button', { name: '重新生成这一张' }).click()
  await expect.poll(async () => (await (await page.request.get(`/api/orders/${order.id}`)).json()).items.reduce((n: number, i: { attempt: number }) => n+i.attempt, 0)).toBe(13)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '重新排版', exact: true }).click()
  await dialog.getByLabel('单张内容长边').fill('85')
  await dialog.getByRole('button', { name: '开始排版' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '打印与预览' }).click()
  await expect(page.locator('.artifact')).toHaveCount(3)
  const download = await page.request.get(`/api/orders/${order.id}/download.zip`)
  expect(download.status()).toBe(200)
  expect(download.headers()['content-type']).toContain('application/zip')

  // Initial download is complete; changed results require an explicit download.
  await page.getByRole('button',{name:'保存到本机',exact:true}).click()
  await expect(page.getByText('已保存到本机',{exact:true})).toBeVisible()
  expect(await page.evaluate(async()=>{
    const root=await navigator.storage.getDirectory()
    const custom=await (await root.getDirectoryHandle('e2e-custom')).getDirectoryHandle('岁岁成品')
    const names=[];for await(const name of custom.keys())names.push(name)
    return names.length
  })).toBe(2)
  await page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    await dir.removeEntry('小满_B001_1.png')
    const writer=await (await dir.getFileHandle('keep.txt',{create:true})).createWritable()
    await writer.write('unrelated');await writer.close()
  })
  await page.reload()
  await page.getByRole('navigation').getByRole('button',{name:'任务中心'}).click()
  await expect(page.locator('.task-row').filter({has:page.getByRole('heading',{name:'小满',exact:true})})).toContainText('已保存到本机')
  expect(await page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    try{await dir.getFileHandle('小满_B001_1.png');return true}catch{return false}
  })).toBe(false)
  await page.getByLabel('选择下载 小满',{exact:true}).check()
  await page.getByRole('button',{name:'重新下载所选订单'}).click()
  await expect.poll(()=>page.evaluate(async()=>{
    try{
      const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
      return (await (await dir.getFileHandle('小满_B001_1.png')).getFile()).size>0
    }catch{return false}
  })).toBe(true)
  await page.getByRole('button',{name:'预览 小满',exact:true}).click()
  await expect(dialog.getByRole('img',{name:'小满 水印预览'})).toBeVisible()
  await expect(dialog.locator('img')).toHaveAttribute('src', /\/preview\?size=1280$/)
  await expect.poll(()=>dialog.locator('img').evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth>0)).toBe(true)
  await dialog.locator('img').evaluate(async (image:HTMLImageElement)=>{await image.decode();await new Promise(requestAnimationFrame)})
  await page.screenshot({path:evidence('order-compressed-preview.png'),animations:'disabled'})
  await dialog.getByRole('button',{name:'查看原图',exact:true}).click()
  await expect(dialog.locator('img')).toHaveAttribute('src', /^\/api\/assets\/[a-f0-9]{32}$/)
  await expect.poll(()=>dialog.locator('img').evaluate((image:HTMLImageElement)=>image.complete&&image.naturalWidth)).toBe(1024)
  expect(await dialog.locator('img').evaluate((image:HTMLImageElement)=>image.naturalWidth)).toBe(1024)
  await dialog.locator('img').evaluate(async (image:HTMLImageElement)=>{await image.decode();await new Promise(requestAnimationFrame)})
  await page.screenshot({path:evidence('order-preview.png'),animations:'disabled'})
  await dialog.getByRole('button',{name:'关闭',exact:true}).click()
  const row=page.locator('.task-row').filter({has:page.getByRole('heading',{name:'小满',exact:true})})
  await row.getByRole('button',{name:'打开目录'}).click()
  await expect.poll(()=>page.evaluate(()=>(window as Window & {openedDirectory?:string}).openedDirectory)).toBe('小满')
  await page.screenshot({path:evidence('order-downloads.png'),animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:evidence('order-downloads-mobile.png'),animations:'disabled'})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button',{name:/小满.*B001/}).click()
  await page.getByRole('button',{name:'重新排版',exact:true}).click()
  await dialog.getByLabel('单张内容长边').fill('50')
  await dialog.getByRole('button',{name:'开始排版'}).click()
  await expect(page.locator('.artifact')).toHaveCount(2)
  await page.getByRole('button',{name:'保存到本机',exact:true}).click()
  await expect.poll(()=>page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    const names=[];for await(const name of dir.keys())names.push(name)
    return names.sort()
  })).toEqual(['keep.txt','小满_B001_1.png','小满_水印总览.png'])
  expect(await page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    return (await (await dir.getFileHandle('keep.txt')).getFile()).text()
  })).toBe('unrelated')

  await page.getByRole('navigation').getByRole('button', { name: '账号设置' }).click()
  await page.getByLabel('水印文字').fill('仅供客户确认')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.locator('.toast')).toContainText('账号设置已保存')
  await page.getByRole('navigation').getByRole('button', { name: '管理设置' }).click()
  await expect(page.getByLabel('FAL API Key')).toHaveAttribute('type', 'password')
  await page.getByLabel('最大同时处理数量').fill('3')
  await page.getByLabel('FAL API Key').fill('fal-test-only-not-a-real-key')
  await page.getByRole('button', { name: '保存全站设置' }).click()
  await expect(page.locator('.toast')).toContainText('全站设置已保存')
  await expect(page.getByLabel('FAL API Key')).toHaveValue('')
  const settings = await (await page.request.get('/api/admin/settings')).json()
  expect(settings.max_inflight).toBe(3)
  expect(settings.fal_configured).toBe(true)
  expect(settings).not.toHaveProperty('rpm')
  expect(settings).not.toHaveProperty('fal_api_key')
  await page.reload()
  await page.getByRole('navigation').getByRole('button', { name: '管理设置' }).click()
  await expect(page.getByLabel('最大同时处理数量')).toHaveValue('3')
  await expect(page.locator('.availability')).toHaveText('已配置密钥')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:evidence('admin-settings-mobile.png'),fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button', { name: '生成邀请码' }).click()
  await expect(page.locator('.invite-code code')).not.toBeEmpty()
  if(await page.getByRole('button',{name:'关闭提示',exact:true}).count())await page.getByRole('button',{name:'关闭提示',exact:true}).click()
  await page.screenshot({ path: evidence('admin-settings.png'), fullPage: true, animations:'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '展开导航' }).click()
  await page.getByRole('navigation').getByRole('button', { name: '工作台', exact: true }).click()
  await expect.poll(()=>page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await page.screenshot({ path: evidence('workspace-mobile.png'), fullPage: true, animations:'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('switching accounts in another tab invalidates drafts before another upload',async({page,browser})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  const invite=await (await page.request.post('/api/admin/invites')).json()
  const isolated=await browser.newContext()
  await isolated.request.post('http://127.0.0.1:5174/api/auth/register',{data:{invite:invite.code,username:'seconduser',password:'second-password',display_name:'第二个账号'}})
  await isolated.close()
  await page.goto('/')
  await page.locator('input[type=file]').setInputFiles({name:'仅属于管理员.png',mimeType:'image/png',buffer:pixel})
  await expect(page.getByLabel('订单名称')).toHaveValue('仅属于管理员')
  const other=await page.context().newPage()
  await other.goto('/')
  await other.getByRole('button',{name:'退出登录'}).click()
  await other.locator('input[name=username]').fill('seconduser')
  await other.locator('input[name=password]').fill('second-password')
  await other.getByRole('button',{name:'登录',exact:true}).click()
  await expect(other.getByRole('heading',{name:'批量制作'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'欢迎回来'})).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  expect(await (await page.request.get('/api/orders')).json()).toEqual([])
  await other.close()
})

test('logout cancels an in-progress batch before a later draft changes accounts',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await installDirectoryPicker(page)
  await page.goto('/')
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles([{name:'A-first.png',mimeType:'image/png',buffer:pixel},{name:'A-second.png',mimeType:'image/png',buffer:pixel}])
  await page.getByRole('button',{name:'批量选择模板'}).click()
  await page.getByRole('dialog').getByRole('button',{name:/春日出游/}).click()
  await page.getByRole('dialog').getByRole('button',{name:/应用到/}).click()
  let release!:()=>void,hit!:()=>void
  const held=new Promise<void>(resolve=>{release=resolve}),reached=new Promise<void>(resolve=>{hit=resolve})
  const initNames:string[]=[]
  page.on('request',request=>{if(request.url().endsWith('/uploads/init'))initNames.push(request.postDataJSON().filename)})
  await page.route('**/api/uploads/*/complete',async route=>{
    const response=await route.fetch()
    hit();await held
    await route.fulfill({response}).catch(()=>{})
  })
  await page.getByRole('button',{name:'提交生成'}).click()
  await reached
  await page.getByRole('button',{name:'退出登录'}).click()
  await page.locator('input[name=username]').fill('seconduser')
  await page.locator('input[name=password]').fill('second-password')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  release()
  await expect(page.getByRole('heading',{name:'批量制作'})).toBeVisible()
  await page.waitForTimeout(700)
  expect(initNames).toEqual(['A-first.png'])
  expect(await (await page.request.get('/api/orders')).json()).toEqual([])
})

test('FAL queue recovery preserves original request and requires confirmation before releasing unknown work', async ({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  const orders=await (await page.request.get('/api/orders')).json()
  const detail=await (await page.request.get(`/api/orders/${orders[0].id}`)).json()
  const endpoint=`/api/orders/${detail.id}`
  Object.assign(detail,{unknown:2,completed:10,status:'unknown'})
  Object.assign(detail.items[0],{status:'unknown',processing_stage:'generate',fal_request_id:'fal-original-request',fal_status:'IN_PROGRESS',remote_reserved:true,recoverable:true,can_resolve:true,error:'FAL连接需要恢复'})
  Object.assign(detail.items[1],{status:'unknown',processing_stage:'generate',fal_request_id:null,fal_status:null,remote_reserved:true,recoverable:false,can_resolve:true,error:'FAL提交响应丢失'})
  const first=detail.items[0], second=detail.items[1]
  const mutations:string[]=[]
  await page.route(`**${endpoint}`,route=>route.fulfill({json:detail}))
  await page.route(`**${endpoint}/items/**`,async route=>{
    const request=route.request(),path=new URL(request.url()).pathname
    expect(request.method()).toBe('POST')
    mutations.push(path)
    if(path.endsWith('/recover'))Object.assign(first,{status:'running',fal_status:'IN_QUEUE',queue_position:2,recoverable:false,can_resolve:false,error:null})
    else if(path.endsWith('/resolve')){
      expect(request.postDataJSON()).toEqual({confirmed_ended:true})
      Object.assign(second,{status:'failed',remote_reserved:false,can_resolve:false,error:'已确认原请求结束'})
    }else throw new Error('Recovery must not submit a new generation')
    await route.fulfill({json:detail})
  })
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'任务中心'}).click()
  await page.getByRole('button',{name:new RegExp(detail.name+'.*B001')}).click()
  await page.getByRole('button',{name:'单张结果'}).click()
  await page.locator('.result-card').first().click()
  const dialog=page.getByRole('dialog')
  await expect(dialog.getByText('fal-original-request',{exact:true})).toBeVisible()
  expect(await dialog.locator('.compare-grid figure').first().locator('img').evaluate(image=>image.getBoundingClientRect().bottom<=image.closest('figure')!.getBoundingClientRect().bottom+1)).toBe(true)
  for(const image of await dialog.locator('.compare-grid img').all()){
    await image.evaluate(async (img:HTMLImageElement)=>{await img.decode();await new Promise(requestAnimationFrame)})
    expect((await image.boundingBox())!.height).toBeGreaterThan(64)
  }
  for(const button of await dialog.locator('.compare-grid').getByRole('button',{name:'查看原图',exact:true}).all())await expect(button).toBeInViewport()
  await page.screenshot({path:evidence('fal-request-unknown.png'),animations:'disabled'})

  await expect(dialog.getByRole('button',{name:/重新生成/})).toBeDisabled()
  await dialog.getByRole('button',{name:'恢复原请求',exact:true}).click()
  await expect(dialog.getByText('FAL 排队中 · 前方 2 个请求',{exact:true})).toBeVisible()
  await expect(dialog.getByText('fal-original-request',{exact:true})).toBeVisible()
  await dialog.getByRole('button',{name:'关闭',exact:true}).click()
  await page.locator('.result-card').nth(1).click()
  await expect(dialog.getByRole('button',{name:'恢复原请求',exact:true})).toHaveCount(0)
  const release=dialog.getByRole('button',{name:'释放并发占用',exact:true})
  await expect(release).toBeDisabled()
  await dialog.getByLabel('我已在 FAL 控制台确认原请求已结束或不存在').check()
  await release.click()
  await expect(dialog.getByRole('button',{name:'重新生成这一张',exact:true})).toBeEnabled()
  expect(mutations).toEqual([`${endpoint}/items/${first.id}/recover`,`${endpoint}/items/${second.id}/resolve`])
  await page.screenshot({path:evidence('fal-recovery.png'),animations:'disabled'})
})

test('avatar and template uploads send resized bytes and single-order search keeps selections',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await installDirectoryPicker(page)
  await page.goto('/')
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  const encoded=await page.evaluate(()=>{
    const canvas=document.createElement('canvas');canvas.width=2048;canvas.height=3072
    const ctx=canvas.getContext('2d')!;ctx.fillStyle='rgba(250,120,60,0.5)';ctx.fillRect(128,128,1792,2816)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  const input=Buffer.from(encoded,'base64')
  await page.getByRole('navigation').getByRole('button',{name:'模板库'}).click()
  await page.getByRole('button',{name:'新建套装',exact:true}).first().click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('套装编号').fill('R1024')
  await dialog.getByLabel('套装名称').fill('压缩测试套装')
  await dialog.locator('input[type=file]').setInputFiles(Array.from({length:12},(_,i)=>({name:`透明模板${i+1}.png`,mimeType:'image/png',buffer:input})))
  // CDP omits multipart file bytes; inspect the actual FormData passed to native fetch.
  await page.evaluate(()=>{
    const native=window.fetch.bind(window),record=window as Window & {templateUploadFiles?:File[];avatarUploadChunks?:Blob[]}
    window.fetch=(url,options)=>{
      if(url==='/api/templates'&&options?.body instanceof FormData)record.templateUploadFiles=options.body.getAll('files') as File[]
      if(typeof url==='string'&&url.startsWith('/api/uploads/')&&options?.method==='PUT'&&options.body instanceof Blob)(record.avatarUploadChunks??=[]).push(options.body)
      return native(url,options)
    }
  })
  const submitted=page.waitForResponse(response=>response.request().method()==='POST'&&new URL(response.url()).pathname==='/api/templates')
  await dialog.getByRole('button',{name:'保存套装',exact:true}).click()
  const response=await submitted
  expect(response.ok()).toBe(true)
  const dimensions=await page.evaluate(async()=>Promise.all(((window as Window & {templateUploadFiles?:File[]}).templateUploadFiles||[]).map(async file=>{
    const header=new DataView(await file.slice(0,24).arrayBuffer())
    return [header.getUint32(16),header.getUint32(20)]
  })))
  expect(dimensions).toEqual(Array.from({length:12},()=>[1024,1536]))
  const saved=await response.json()
  const stored=await (await page.request.get(saved.images[0].url)).body()
  expect([stored.readUInt32BE(16),stored.readUInt32BE(20)]).toEqual([1024,1536])
  await expect(dialog).not.toBeVisible()
  await page.getByRole('navigation').getByRole('button',{name:'工作台',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:'订单压缩.png',mimeType:'image/png',buffer:input})
  await page.getByRole('button',{name:'选择模板',exact:true}).click()
  await dialog.getByLabel('搜索模板套装').fill('r1024')
  await dialog.getByRole('button',{name:/压缩测试套装/}).click()
  await dialog.getByLabel('搜索模板套装').fill('春日')
  await dialog.getByRole('button',{name:/春日出游/}).click()
  await dialog.getByLabel('搜索模板套装').fill('匹配不到')
  await expect(dialog.getByText('已选 2 套 · 24 张')).toBeVisible()
  await dialog.getByRole('button',{name:'清空搜索',exact:true}).click()
  await expect(dialog.locator('.template-option.selected')).toHaveCount(2)
  await page.screenshot({path:evidence('template-search.png'),animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  expect(await dialog.evaluate(element=>element.scrollWidth<=element.clientWidth)).toBe(true)
  await page.screenshot({path:evidence('template-search-mobile.png'),animations:'disabled'})
  await page.setViewportSize({width:1440,height:1000})
  await dialog.getByRole('button',{name:'应用到 1 个订单'}).click()
  await page.getByRole('button',{name:'提交生成',exact:true}).click()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  const uploaded=await page.evaluate(async()=>{
    const blob=new Blob((window as Window & {avatarUploadChunks?:Blob[]}).avatarUploadChunks||[])
    const header=new DataView(await blob.slice(0,24).arrayBuffer())
    return {dimensions:[header.getUint32(16),header.getUint32(20)],size:blob.size}
  })
  expect(uploaded.dimensions).toEqual([1024,1536])
  expect(uploaded.size).toBeLessThan(input.byteLength)
  const orders=await(await page.request.get('/api/orders')).json()
  const order=orders.find((row:{name:string})=>row.name==='订单压缩')
  expect(order.template_codes).toEqual(['R1024','B001'])
  const avatar=await(await page.request.get(order.avatar_url)).body()
  expect([avatar.readUInt32BE(16),avatar.readUInt32BE(20)]).toEqual([1024,1536])
})


test('duplicate name rejection stays editable and destination binding is atomic',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await installDirectoryPicker(page,'retry-output')
  await page.goto('/')
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:'小满.png',mimeType:'image/png',buffer:pixel})
  await page.getByRole('button',{name:'选择模板',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/春日出游/}).click()
  await page.getByRole('dialog').getByRole('button',{name:'应用到 1 个订单'}).click()
  await page.getByRole('button',{name:'提交生成',exact:true}).click()
  await expect(page.locator('.draft-status')).toContainText('修改名称')
  await expect(page.getByLabel('订单名称')).toBeEnabled()
  await page.getByLabel('订单名称').fill('改名后成功')
  await page.getByRole('button',{name:'提交生成',exact:true}).click()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  const binding=await page.evaluate(async()=>{
    const path='/src/lib/device.ts',db='/src/lib/db.ts'
    const {bindDestination}=await import(path),{readLocal}=await import(db)
    const root=await navigator.storage.getDirectory()
    const a=await root.getDirectoryHandle('binding-a',{create:true}),b=await root.getDirectoryHandle('binding-b',{create:true})
    const [first,second]=await Promise.all([bindDestination('fixture','same-token',a),bindDestination('fixture','same-token',b)])
    const persisted=await readLocal('destination:fixture:same-token')
    return await first.isSameEntry(second)&&await first.isSameEntry(persisted)
  })
  expect(binding).toBe(true)
})

test('uncertain submission retry keeps its locked identity after an upload failure',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await installDirectoryPicker(page,'uncertain-output')
  await page.goto('/')
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  await page.locator('input[type=file]').setInputFiles({name:'待确认订单.png',mimeType:'image/png',buffer:pixel})
  await page.getByRole('button',{name:'选择模板',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:/春日出游/}).click()
  await page.getByRole('dialog').getByRole('button',{name:'应用到 1 个订单'}).click()
  await page.route('**/api/orders',route=>route.request().method()==='POST'?route.abort('failed'):route.continue())
  await page.getByRole('button',{name:'提交生成',exact:true}).click()
  await expect(page.locator('.draft-status')).toContainText('Failed to fetch')
  await expect(page.getByLabel('订单名称')).toBeDisabled()
  await page.route('**/api/uploads/init',route=>route.fulfill({status:400,json:{detail:'模拟上传失败'}}))
  await page.getByRole('button',{name:'提交生成',exact:true}).click()
  await expect(page.locator('.draft-status')).toHaveText('模拟上传失败')
  await expect(page.getByLabel('订单名称')).toBeDisabled()
  await expect(page.getByTitle('单独选择此订单的保存位置')).toBeDisabled()
})

test('batch re-download chooses one destination and cancellation writes nothing',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  const rows=(await(await page.request.get('/api/orders')).json()).filter((order:{download_ready:boolean})=>order.download_ready).slice(0,2)
  expect(rows).toHaveLength(2)
  await installDirectoryPicker(page,'manual-download')
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'任务中心'}).click()
  for(const order of rows)await page.getByLabel('选择下载 '+order.name,{exact:true}).check()
  await page.getByRole('button',{name:'重新下载所选订单'}).click()
  await expect(page.getByRole('button',{name:'重新下载所选订单'})).toBeEnabled()
  expect(await page.evaluate(()=>(window as Window & {pickerCalls?:number}).pickerCalls)).toBe(1)
  const savedNames=await page.evaluate(async()=>{
    const root=await (await navigator.storage.getDirectory()).getDirectoryHandle('manual-download')
    const names=[];for await(const name of root.keys())names.push(name)
    return names.sort()
  })
  expect(savedNames).toEqual(rows.map((order:{name:string})=>order.name).sort())
  await expect(page.locator('.directory-button')).toHaveText('选择保存目录')
  let manifests=0
  page.on('request',request=>{if(request.url().endsWith('/manifest'))manifests++})
  await page.evaluate(()=>{(window as Window & {pickerCancel?:boolean}).pickerCancel=true})
  await page.getByRole('button',{name:'重新下载所选订单'}).click()
  await expect(page.getByRole('button',{name:'重新下载所选订单'})).toBeEnabled()
  expect(await page.evaluate(()=>(window as Window & {pickerCalls?:number}).pickerCalls)).toBe(2)
  expect(manifests).toBe(0)
})

test('submission date periods intersect search results',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  const base=(await(await page.request.get('/api/orders')).json())[0]
  const rows=[0.5,2,5,15,40].map(days=>({...base,id:'date-'+days,name:'日期测试 '+days,created_at:new Date(Date.now()-days*86400000).toISOString(),download_ready:false,artifact_version:0,preview_url:null}))
  await page.route('**/api/orders',route=>route.fulfill({json:rows}))
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'任务中心'}).click()
  await expect(page.locator('.task-row time')).toHaveCount(5)
  for(const [days,count]of [['1',1],['3',2],['7',3],['30',4],['0',5]] as const){
    await page.getByLabel('提交时间范围').selectOption(days)
    await expect(page.locator('.task-row')).toHaveCount(count)
  }
  await page.getByLabel('搜索订单',{exact:true}).fill('日期测试 5')
  await page.getByLabel('提交时间范围').selectOption('3')
  await expect(page.locator('.task-row')).toHaveCount(0)
  await page.getByLabel('提交时间范围').selectOption('7')
  await expect(page.locator('.task-row')).toHaveCount(1)
  await page.screenshot({path:evidence('order-date-search.png'),animations:'disabled'})
})

test('admin cleanup previews scope then removes isolated orders while preserving templates',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await expect.poll(async()=>(await(await page.request.get('/api/orders')).json()).every((o:{download_ready:boolean})=>o.download_ready),{timeout:40000}).toBe(true)
  const templates=await(await page.request.get('/api/templates')).json()
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'管理设置'}).click()
  await expect(page.getByText('磁盘总容量',{exact:true})).toBeVisible()
  await page.getByLabel('清理此日期之前的订单').fill('2027-01-01')
  await page.getByRole('button',{name:'预览清理范围'}).click()
  const dialog=page.getByRole('dialog')
  await expect(dialog.getByRole('heading',{name:'确认清理服务器订单'})).toBeVisible()
  await expect(dialog.getByRole('button',{name:'确认永久清理'})).toBeDisabled()
  await page.screenshot({path:evidence('admin-cleanup-confirm.png'),animations:'disabled'})
  await dialog.getByLabel('我确认永久删除上述服务器订单及文件').check()
  await dialog.getByRole('button',{name:'确认永久清理'}).click()
  await expect(dialog).not.toBeVisible()
  expect(await(await page.request.get('/api/orders')).json()).toEqual([])
  expect(await(await page.request.get('/api/templates')).json()).toEqual(templates)
  await page.locator('.maintenance-panel').scrollIntoViewIfNeeded()
  await page.screenshot({path:evidence('admin-storage.png'),animations:'disabled'})
})
