import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'

// Small opaque input is intentional: the injected provider supplies transparent output.
const pixel = readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
const files = Array.from({ length: 12 }, (_, i) => ({ name: `template-${i+1}.png`, mimeType: 'image/png', buffer: pixel }))

test('complete production UI workflow with isolated provider and data', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message=>{if(message.type()==='error')errors.push(message.text())})
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '创建管理员账号' })).toBeVisible()
  await page.getByLabel('显示名称', { exact: true }).fill('联调管理员')
  await page.getByLabel('账号', { exact: true }).fill('testadmin')
  await page.locator('input[name=password]').fill('local-test-password')
  await page.getByRole('button', { name: '创建并进入工作台' }).click()
  await expect(page.getByRole('heading', { name: '批量制作' })).toBeVisible()
  await page.screenshot({ path: '../docs/design/workspace-empty.png', fullPage: true })

  await page.getByRole('navigation').getByRole('button', { name: '模板库' }).click()
  await page.getByRole('button', { name: '新建套装' }).first().click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('套装编号').pressSequentially('B001')
  await expect(dialog.getByLabel('套装编号')).toHaveValue('B001')
  await dialog.getByLabel('套装名称').pressSequentially('春日出游')
  await expect(dialog.getByLabel('套装名称')).toHaveValue('春日出游')
  await dialog.locator('input[type=file]').setInputFiles(files)
  await dialog.getByRole('button', { name: '保存套装' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('heading', { name: '春日出游' })).toBeVisible()

  await page.getByRole('navigation').getByRole('button', { name: '工作台', exact: true }).click()
  await page.locator('input[type=file]').setInputFiles([{ name: '小满.png', mimeType: 'image/png', buffer: pixel }, { name: '岁岁.png', mimeType: 'image/png', buffer: pixel }])
  await expect(page.getByLabel('订单名称')).toHaveCount(2)
  await page.getByRole('button', { name: '批量选择模板' }).click()
  await dialog.getByRole('button', { name: /春日出游/ }).click()
  await dialog.getByRole('button', { name: '应用到 2 个订单' }).click()
  await page.getByRole('button', { name: '打印参数', exact: true }).click()
  await dialog.getByLabel('单张内容长边').fill('50')
  await dialog.getByRole('button', { name: '保存参数' }).click()
  await expect(page.getByText('预计生成')).toBeVisible()
  await expect(page.locator('.print-summary').first()).toContainText('5 cm')
  await expect(page.getByText('草稿已保存',{exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('订单名称')).toHaveCount(2)
  await expect(page.locator('.print-summary').first()).toContainText('5 cm')
  await page.screenshot({ path: '../docs/design/workspace-orders.png', fullPage: true })
  await page.getByRole('button', { name: '提交生成' }).click()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button', { name: '任务中心' }).click()
  await expect(page.getByRole('heading', { name: '小满', exact: true })).toBeVisible()
  await expect.poll(async () => (await page.request.get('/api/orders')).json().then(rows => rows.every((o: { status: string }) => o.status === 'completed')), { timeout: 40000 }).toBe(true)
  const orders = await (await page.request.get('/api/orders')).json()
  const order = orders.find((o: { name: string }) => o.name === '小满')
  await page.getByRole('button', { name: /小满.*B001/ }).click()
  await expect(page.locator('.artifact')).toHaveCount(2)
  await expect(page.getByText('尚未保存', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '单张结果' }).click()
  await page.locator('.result-card').first().click()
  await expect(dialog.getByRole('heading')).toHaveText('B001 · 第 1 张')
  await page.screenshot({path:'../docs/design/result-review.png',animations:'disabled'})
  await dialog.getByRole('button', { name: '重新生成这一张' }).click()
  await expect.poll(async () => (await (await page.request.get(`/api/orders/${order.id}`)).json()).items.reduce((n: number, i: { attempt: number }) => n+i.attempt, 0)).toBe(13)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '重新排版', exact: true }).click()
  await dialog.getByLabel('单张内容长边').fill('85')
  await dialog.getByRole('button', { name: '开始排版' }).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button', { name: '打印与预览' }).click()
  await expect(page.locator('.artifact')).toHaveCount(3)
  const download = await page.request.get(`/api/orders/${order.id}/download.zip`)
  expect(download.status()).toBe(200)
  expect(download.headers()['content-type']).toContain('application/zip')

  // Use real browser FileSystem handles and IndexedDB; only the native chooser is substituted.
  await page.evaluate(async()=>{
    const output=await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output',{create:true})
    window.showDirectoryPicker=async()=>output
  })
  await page.getByRole('button',{name:'选择保存目录',exact:true}).click()
  await expect(page.getByText('已保存到本机',{exact:true})).toBeVisible()
  await page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    await dir.removeEntry('小满_B001_1.png')
    const writer=await (await dir.getFileHandle('keep.txt',{create:true})).createWritable()
    await writer.write('unrelated');await writer.close()
  })
  await page.reload()
  await expect.poll(()=>page.evaluate(async()=>{
    try{
      const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
      return (await (await dir.getFileHandle('小满_B001_1.png')).getFile()).size>0
    }catch{return false}
  })).toBe(true)
  await page.getByRole('navigation').getByRole('button',{name:'任务中心'}).click()
  await page.getByRole('button',{name:/小满.*B001/}).click()
  await page.getByRole('button',{name:'重新排版',exact:true}).click()
  await dialog.getByLabel('单张内容长边').fill('50')
  await dialog.getByRole('button',{name:'开始排版'}).click()
  await expect(page.locator('.artifact')).toHaveCount(2)
  await expect.poll(()=>page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    const names=[];for await(const name of dir.keys())names.push(name)
    return names.sort()
  })).toEqual(['keep.txt','小满_B001_1.png','小满_水印总览.png'])
  expect(await page.evaluate(async()=>{
    const dir=await (await (await navigator.storage.getDirectory()).getDirectoryHandle('e2e-output')).getDirectoryHandle('小满')
    return (await (await dir.getFileHandle('keep.txt')).getFile()).text()
  })).toBe('unrelated')

  await page.getByRole('navigation').getByRole('button', { name: '账号设置' }).click()
  await page.getByLabel('水印文字').fill('仅供客户确认')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.locator('.toast')).toContainText('账号设置已保存')
  await page.getByRole('navigation').getByRole('button', { name: '管理设置' }).click()
  await expect(page.getByLabel('OpenAI API Key')).toHaveAttribute('type', 'password')
  await page.getByRole('button', { name: '生成邀请码' }).click()
  await expect(page.locator('.invite-code code')).not.toBeEmpty()
  if(await page.getByRole('button',{name:'关闭提示',exact:true}).count())await page.getByRole('button',{name:'关闭提示',exact:true}).click()
  await page.screenshot({ path: '../docs/design/admin-settings.png', fullPage: true, animations:'disabled' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '展开导航' }).click()
  await page.getByRole('navigation').getByRole('button', { name: '工作台', exact: true }).click()
  await expect.poll(()=>page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await page.screenshot({ path: '../docs/design/workspace-mobile.png', fullPage: true, animations:'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('switching accounts in another tab invalidates drafts before another upload',async({page,browser})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  const invite=await (await page.request.post('/api/admin/invites')).json()
  const isolated=await browser.newContext()
  await isolated.request.post('http://127.0.0.1:5174/api/auth/register',{data:{invite:invite.code,username:'seconduser',password:'second-password',display_name:'第二个账号'}})
  await isolated.close()
  await page.goto('/')
  await page.locator('input[type=file]').setInputFiles({name:'仅属于管理员.png',mimeType:'image/png',buffer:pixel})
  await expect(page.getByLabel('订单名称')).toHaveValue('仅属于管理员')
  const other=await page.context().newPage()
  await other.goto('/')
  await other.getByRole('button',{name:'退出登录'}).click()
  await other.locator('input[name=username]').fill('seconduser')
  await other.locator('input[name=password]').fill('second-password')
  await other.getByRole('button',{name:'登录',exact:true}).click()
  await expect(other.getByRole('heading',{name:'批量制作'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'欢迎回来'})).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('订单名称')).toHaveCount(0)
  expect(await (await page.request.get('/api/orders')).json()).toEqual([])
  await other.close()
})

test('logout cancels an in-progress batch before a later draft changes accounts',async({page})=>{
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await page.goto('/')
  await page.locator('input[type=file]').setInputFiles([{name:'A-first.png',mimeType:'image/png',buffer:pixel},{name:'A-second.png',mimeType:'image/png',buffer:pixel}])
  await page.getByRole('button',{name:'批量选择模板'}).click()
  await page.getByRole('dialog').getByRole('button',{name:/春日出游/}).click()
  await page.getByRole('dialog').getByRole('button',{name:/应用到/}).click()
  let release!:()=>void,hit!:()=>void
  const held=new Promise<void>(resolve=>{release=resolve}),reached=new Promise<void>(resolve=>{hit=resolve})
  const initNames:string[]=[]
  page.on('request',request=>{if(request.url().endsWith('/uploads/init'))initNames.push(request.postDataJSON().filename)})
  await page.route('**/api/uploads/*/complete',async route=>{
    const response=await route.fetch()
    hit();await held
    await route.fulfill({response}).catch(()=>{})
  })
  await page.getByRole('button',{name:'提交生成'}).click()
  await reached
  await page.getByRole('button',{name:'退出登录'}).click()
  await page.locator('input[name=username]').fill('seconduser')
  await page.locator('input[name=password]').fill('second-password')
  await page.getByRole('button',{name:'登录',exact:true}).click()
  release()
  await expect(page.getByRole('heading',{name:'批量制作'})).toBeVisible()
  await page.waitForTimeout(700)
  expect(initNames).toEqual(['A-first.png'])
  expect(await (await page.request.get('/api/orders')).json()).toEqual([])
})
