import {uploadStickers,chooseStickers} from './library-fixtures'
import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {tmpdir} from 'node:os'
import {join} from 'node:path'

const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
test('account creation, organization library permission, generation without credits and password reset',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true}).click()
  await page.getByRole('button',{name:'创建成员',exact:true}).click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('用户名',{exact:true}).fill('creditmember')
  await dialog.getByLabel('显示名称',{exact:true}).fill('积分测试成员')
  await dialog.getByRole('button',{name:'创建账号',exact:true}).click()
  await expect(dialog.locator('code')).not.toBeEmpty()
  const password=await dialog.locator('code').innerText()
  await dialog.getByRole('button',{name:'已保存，关闭',exact:true}).click()
  const user=(await (await page.request.get('/api/admin/users')).json()).find((u:{username:string})=>u.username==='creditmember')
  const row=page.locator('.accounts-table tbody tr').filter({hasText:'积分测试成员'})
  await expect(page.getByText('积分与流水',{exact:true})).toHaveCount(0)
  expect(user.credits).toBeUndefined()
  const memberContext=await browser.newContext({baseURL:`http://127.0.0.1:${process.env.STUDIO_E2E_FRONTEND_PORT||'5174'}`,viewport:{width:1440,height:1000}})
  try {
    const member=await memberContext.newPage()
    await member.request.post('/api/auth/login',{data:{username:'creditmember',password}})
    await member.goto('/')
    await expect(member.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true})).toHaveCount(0)
    await member.getByRole('navigation').getByRole('button',{name:'模板库',exact:true}).click()
    await expect(member.getByRole('button',{name:'新建套装',exact:true})).toHaveCount(0)
    expect((await member.request.post('/api/templates',{data:{code:'DENIED',name:'denied',category:'boy',sticker_ids:['permission-probe']}})).status()).toBe(403)
    await row.getByRole('checkbox',{name:'积分测试成员 公共库编辑权限'}).check()
    await expect.poll(async()=>(await(await member.request.get('/api/auth/me')).json()).can_edit_library).toBe(true)
    const assets=await uploadStickers(member.request,Array.from({length:12},(_,i)=>({name:`member-${i}.png`,mimeType:'image/png',buffer:pixel})))
    await member.reload()
    await member.getByRole('navigation').getByRole('button',{name:'模板库',exact:true}).click()
    await member.getByRole('button',{name:'新建套装',exact:true}).first().click()
    const edit=member.getByRole('dialog')
    await edit.getByLabel('套装编号').fill('PERSONAL-ANIMAL')
    await edit.getByLabel('套装名称').fill('动物公共模板')
    await edit.getByRole('combobox',{name:/^分类/}).selectOption('animal')
    await chooseStickers(edit,assets.map(s=>s.code))
    await edit.getByRole('button',{name:'保存套装',exact:true}).click()
    await expect(edit).toHaveCount(0)
    await expect(member.getByRole('heading',{name:'动物公共模板',exact:true})).toBeVisible()
    const sets=await (await member.request.get('/api/templates')).json()
    const personal=sets.find((t:{code:string})=>t.code==='PERSONAL-ANIMAL'),pub=sets.find((t:{code:string;active:boolean})=>t.active&&t.code==='B001')
    expect(personal.category).toBe('animal');expect(pub).toBeTruthy()
    await member.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','personal-templates.png'),fullPage:true})
    const u=await (await member.request.post('/api/uploads/init',{data:{filename:'积分头像.png',size:pixel.length,sha256:createHash('sha256').update(pixel).digest('hex')}})).json()
    await member.request.put('/api/uploads/'+u.id,{data:pixel,headers:{'Upload-Offset':'0'}})
    await member.request.post('/api/uploads/'+u.id+'/complete')
    const response=await member.request.post('/api/orders',{data:{upload_id:u.id,name:'积分联调订单',template_ids:[pub.id,personal.id],print_settings:{long_edge_mm:50},client_token:'credit-browser-order'}})
    expect(response.ok()).toBeTruthy()
    const generated=await response.json()
    await expect.poll(async()=>(await(await member.request.get('/api/orders/'+generated.id)).json()).download_ready,{timeout:60000}).toBe(true)
    await member.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
    await expect(member.getByText('可用积分',{exact:true})).toHaveCount(0)
    await member.setViewportSize({width:390,height:844})
    expect(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await member.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','credits-mobile.png'),fullPage:true})
    await row.getByRole('button',{name:'重置密码',exact:true}).click()
    await dialog.getByRole('button',{name:'确认重置',exact:true}).click()
    await expect(dialog.locator('code')).not.toBeEmpty()
    expect((await member.request.get('/api/auth/me')).status()).toBe(401)
    const next=await dialog.locator('code').innerText()
    expect((await member.request.post('/api/auth/login',{data:{username:'creditmember',password:next}})).ok()).toBeTruthy()
    await dialog.getByRole('button',{name:'已保存，关闭',exact:true}).click()
  } finally {await memberContext.close()}
  expect(errors).toEqual([])
})
