import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {tmpdir} from 'node:os'
import {join} from 'node:path'

const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
test('account creation, credit conflict, private library, successful billing and password reset',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true}).click()
  await page.getByRole('button',{name:'创建成员',exact:true}).click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('用户名',{exact:true}).fill('creditmember')
  await dialog.getByLabel('显示名称',{exact:true}).fill('积分测试成员')
  await dialog.getByRole('button',{name:'创建账号',exact:true}).click()
  await expect(dialog.locator('code')).not.toBeEmpty()
  const password=await dialog.locator('code').innerText()
  await dialog.getByRole('button',{name:'已保存，关闭',exact:true}).click()
  const user=(await (await page.request.get('/api/admin/users')).json()).find((u:{username:string})=>u.username==='creditmember')
  const row=page.locator('.accounts-table tbody tr').filter({hasText:'积分测试成员'})
  await row.getByRole('button',{name:'积分与流水',exact:true}).click()
  await page.getByRole('button',{name:'调整积分',exact:true}).click()
  await dialog.getByLabel('增加积分',{exact:true}).fill('24')
  await dialog.getByLabel('调整原因').fill('联调测试')
  // Another admin adjustment occurs while the dialog is open.
  expect((await page.request.post('/api/admin/users/'+user.id+'/credits',{data:{operation:'add',amount:1,reason:'并发调整',client_token:'browser-credit-before',expected_version:0}})).ok()).toBeTruthy()
  await dialog.getByRole('button',{name:'确认调整',exact:true}).click()
  await expect(dialog.getByRole('alert')).toContainText('余额已变化')
  await expect(dialog.getByText(/当前可用 1 · 冻结 0/)).toBeVisible()
  await dialog.getByRole('button',{name:'确认调整',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'调整可用积分',exact:true})).toHaveCount(0)
  await expect(page.locator('.credits-summary strong').first()).toHaveText('25')
  await page.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','credits-admin.png'),fullPage:true})

  const memberContext=await browser.newContext({baseURL:'http://127.0.0.1:5174',viewport:{width:1440,height:1000}})
  try {
    const member=await memberContext.newPage()
    await member.request.post('/api/auth/login',{data:{username:'creditmember',password}})
    await member.goto('/')
    await expect(member.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true})).toHaveCount(0)
    await member.getByRole('navigation').getByRole('button',{name:'模板库',exact:true}).click()
    await member.getByRole('button',{name:'新建套装',exact:true}).first().click()
    const edit=member.getByRole('dialog')
    await edit.getByLabel('套装编号').fill('PERSONAL-ANIMAL')
    await edit.getByLabel('套装名称').fill('动物个人模板')
    await edit.getByRole('combobox',{name:/^分类/}).selectOption('animal')
    await edit.locator('input[type=file]').setInputFiles(Array.from({length:12},(_,i)=>({name:`private-${i}.png`,mimeType:'image/png',buffer:pixel})))
    await edit.getByRole('button',{name:'保存套装',exact:true}).click()
    await expect(edit).toHaveCount(0)
    await member.getByRole('button',{name:'个人模板',exact:true}).click()
    await expect(member.getByRole('heading',{name:'动物个人模板',exact:true})).toBeVisible()
    const sets=await (await member.request.get('/api/templates')).json()
    const personal=sets.find((t:{code:string})=>t.code==='PERSONAL-ANIMAL'),pub=sets.find((t:{scope:string;active:boolean})=>t.scope==='public'&&t.active)
    expect(personal.category).toBe('animal');expect(pub).toBeTruthy()
    await member.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','personal-templates.png'),fullPage:true})
    const u=await (await member.request.post('/api/uploads/init',{data:{filename:'积分头像.png',size:pixel.length,sha256:createHash('sha256').update(pixel).digest('hex')}})).json()
    await member.request.put('/api/uploads/'+u.id,{data:pixel,headers:{'Upload-Offset':'0'}})
    await member.request.post('/api/uploads/'+u.id+'/complete')
    const response=await member.request.post('/api/orders',{data:{upload_id:u.id,name:'积分联调订单',template_ids:[pub.id,personal.id],print_settings:{long_edge_mm:50},client_token:'credit-browser-order'}})
    expect(response.ok()).toBeTruthy()
    await expect.poll(async()=> (await (await member.request.get('/api/credits')).json()).wallet.spent,{timeout:60000}).toBe(24)
    const wallet=(await (await member.request.get('/api/credits')).json()).wallet
    expect(wallet.available).toBe(1);expect(wallet.frozen).toBe(0)
    await member.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
    await expect(member.locator('.credits-summary strong').nth(2)).toHaveText('24')
    await member.setViewportSize({width:390,height:844})
    expect(await member.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await member.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','credits-mobile.png'),fullPage:true})
    await page.getByRole('dialog',{name:'积分测试成员 · 积分与流水',exact:true}).getByRole('button',{name:'关闭',exact:true}).click()
    await row.getByRole('button',{name:'重置密码',exact:true}).click()
    await dialog.getByRole('button',{name:'确认重置',exact:true}).click()
    await expect(dialog.locator('code')).not.toBeEmpty()
    expect((await member.request.get('/api/auth/me')).status()).toBe(401)
    const next=await dialog.locator('code').innerText()
    expect((await member.request.post('/api/auth/login',{data:{username:'creditmember',password:next}})).ok()).toBeTruthy()
    await dialog.getByRole('button',{name:'已保存，关闭',exact:true}).click()
  } finally {await memberContext.close()}
  expect(errors).toEqual([])
})
