import {test,expect} from '@playwright/test'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
test('credit dialog preserves account search and nested adjustment focus',async({page})=>{
  const setup=await page.request.post('/api/auth/setup',{data:{username:'modaladmin',password:'modal-test-password',display_name:'弹窗验收管理员'}})
  await page.request.post('/api/auth/login',{data:setup.ok()?{username:'modaladmin',password:'modal-test-password'}:{username:'testadmin',password:'local-test-password'}})
  const member=await(await page.request.post('/api/admin/users',{data:{username:'modalmember',display_name:'弹窗验收成员'}})).json()
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true}).click()
  await page.getByRole('textbox',{name:'搜索账号'}).fill('modalmember')
  await page.getByRole('button',{name:'积分与流水',exact:true}).click()
  const ledger=page.getByRole('dialog',{name:'弹窗验收成员 · 积分与流水',exact:true})
  await expect(ledger).toBeVisible()
  await ledger.getByRole('button',{name:'调整积分',exact:true}).click()
  const adjust=page.getByRole('dialog',{name:'调整可用积分',exact:true})
  await expect(adjust).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(adjust).toHaveCount(0)
  await expect(ledger).toBeVisible()
  await expect(ledger.getByRole('button',{name:'调整积分',exact:true})).toBeFocused()
  await ledger.getByRole('button',{name:'调整积分',exact:true}).click()
  await adjust.getByLabel('增加积分',{exact:true}).fill('7')
  await adjust.getByLabel('调整原因').fill('隔离浏览器验收')
  await adjust.getByRole('button',{name:'确认调整',exact:true}).click()
  await expect(adjust).toHaveCount(0)
  await expect(ledger.locator('.credits-summary strong').first()).toHaveText('7')
  await page.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','credits-dialog.png'),animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  await expect(ledger).toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','credits-dialog-mobile.png'),animations:'disabled'})
  await page.keyboard.press('Escape')
  await expect(ledger).toHaveCount(0)
  await expect(page.getByRole('textbox',{name:'搜索账号'})).toHaveValue('modalmember')
  await expect(page.locator('.accounts-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.accounts-table tbody tr td').nth(1)).toHaveText('7')
  expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden')
  expect((await(await page.request.get('/api/admin/users/'+member.user.id+'/credits')).json()).wallet.available).toBe(7)
})
