import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'

test.use({timezoneId:'Asia/Taipei'})
test('calendar dates include both boundary days and intersect search and status filters',async({page})=>{
  const setup=await page.request.post('/api/auth/setup',{data:{username:'calendaradmin',password:'calendar-test-password',display_name:'日期验收'}})
  await page.request.post('/api/auth/login',{data:setup.ok()?{username:'calendaradmin',password:'calendar-test-password'}:{username:'testadmin',password:'local-test-password'}})
  await page.clock.setFixedTime(new Date('2026-09-07T04:00:00Z'))
  const avatar='data:image/png;base64,'+readFileSync(new URL('./fixtures/portrait.png',import.meta.url)).toString('base64')
  const rows=[['previous','2026-09-06T23:59:59.999+08:00'],['start','2026-09-07T00:00:00+08:00'],['end','2026-09-07T23:59:59.999+08:00'],['next','2026-09-08T00:00:00+08:00'],['range-end','2026-09-09T23:59:59.999+08:00'],['after','2026-09-10T00:00:00+08:00'],['unrelated','2026-09-07T10:00:00+08:00']].map(([id,created_at])=>({id:'calendar-'+id,name:'日期 '+id,created_at,status:id==='start'?'completed':'queued',total:1,completed:id==='start'?1:0,failed:0,unknown:0,paused:false,avatar_url:avatar,template_codes:[id==='unrelated'?'OTHER':'A1-13'],print_settings:{paper_width_mm:210,paper_height_mm:297,long_edge_mm:85,margin_mm:10,gap_mm:10,dpi:300,brightness:false,color_balance:false},artifact_version:0,artifacts:[],items:[],download_ready:false}))
  await page.route('**/api/orders',r=>r.fulfill({json:rows}))
  await page.route('**/api/orders/calendar-*',r=>r.fulfill({json:rows.find(o=>r.request().url().endsWith(o.id))}))
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'历史订单',exact:true}).click()
  const period=page.getByLabel('提交时间范围'),tasks=page.locator('.task-row')
  await period.selectOption('today')
  await expect(tasks).toHaveCount(3)
  await page.getByLabel('搜索订单',{exact:true}).fill('A1 13')
  await expect(tasks).toHaveCount(2)
  await page.getByRole('button',{name:'已完成',exact:true}).click()
  await expect(tasks).toHaveCount(1);await expect(tasks).toContainText('日期 start')
  await page.getByRole('button',{name:'处理中',exact:true}).click()
  await expect(tasks).toHaveCount(1);await expect(tasks).toContainText('日期 end')
  await page.getByRole('button',{name:'全部',exact:true}).click()
  await period.selectOption('date')
  await page.getByLabel('提交日期',{exact:true}).fill('2026-09-06')
  await expect(tasks).toHaveCount(1);await expect(tasks).toContainText('日期 previous')
  await period.selectOption('range')
  await page.getByLabel('开始日期',{exact:true}).fill('2026-09-07')
  await page.getByLabel('结束日期',{exact:true}).fill('2026-09-09')
  await expect(tasks).toHaveCount(4)
  await tasks.first().getByRole('button',{name:'查看详情',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(period).toHaveValue('range')
  await expect(page.getByLabel('开始日期',{exact:true})).toHaveValue('2026-09-07')
  await expect(tasks).toHaveCount(4)
  await page.screenshot({path:'/tmp/avatar-studio-fal-qa/order-calendar-desktop.png'})
  await page.setViewportSize({width:390,height:844})
  await expect(page.locator('.sidebar')).not.toBeInViewport()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'/tmp/avatar-studio-fal-qa/order-calendar-mobile.png',fullPage:true,animations:'disabled'})
  await page.getByLabel('开始日期',{exact:true}).fill('2026-09-10')
  await expect(page.getByRole('alert')).toHaveText('开始日期不能晚于结束日期')
  await expect(tasks).toHaveCount(0)
  await page.getByLabel('结束日期',{exact:true}).fill('')
  await expect(page.getByRole('alert')).toHaveText('请选择有效的开始和结束日期')
  await period.selectOption('0')
  await expect(tasks).toHaveCount(6)
  await expect(page.getByRole('alert')).toHaveCount(0)
})
