import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {uploadStickers} from './library-fixtures'
test('mixed public selections deduplicate generation and retain every exported copy',async({page})=>{
 const status=await (await page.request.get('/api/auth/status')).json()
 if(status.needs_setup)await page.request.post('/api/auth/setup',{data:{username:'testadmin',password:'local-test-password',display_name:'测试管理员'}})
 else await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
 const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
 const stickers=await uploadStickers(page.request,[{name:'MIX-one.png',mimeType:'image/png',buffer:pixel},{name:'MIX-two.png',mimeType:'image/png',buffer:pixel}])
 const sets=[]
 for(const code of ['MIX-A','MIX-B']){const response=await page.request.post('/api/templates',{data:{code,name:code,category:'general',sticker_ids:[stickers[0].id]}});expect(response.ok()).toBeTruthy();sets.push(await response.json())}
 await page.goto('/')
 await page.locator('input[type=file]').setInputFiles({name:'混合验收.png',mimeType:'image/png',buffer:pixel})
 await page.getByRole('button',{name:'批量选择模板'}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByLabel('搜索模板套装').fill('MIX-')
 for(const code of ['MIX-A','MIX-B'])await dialog.getByRole('button',{name:new RegExp(code)}).click()
 await dialog.getByRole('button',{name:'单张贴纸',exact:true}).click()
 await dialog.getByLabel('搜索贴纸').fill('MIX-')
 for(const s of stickers)await dialog.locator('.template-option').filter({hasText:s.code}).click()
 await expect(dialog.getByText(/实际生成 2 张 · 导出 4 张/)).toBeVisible()
 await dialog.locator('summary').click()
 await expect(dialog.locator('.preview-template-grid figure')).toHaveCount(4)
 await page.screenshot({path:'/tmp/avatar-studio-fal-qa/mixed-selection-desktop.png'})
 await page.setViewportSize({width:390,height:844})
 expect(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true)
 await page.screenshot({path:'/tmp/avatar-studio-fal-qa/mixed-selection-mobile.png'})
 await dialog.getByRole('button',{name:'应用到 1 个订单'}).click()
 await expect(page.locator('.submit-bar')).toContainText('预计生成 2 张 · 导出 4 张')
 const upload=await (await page.request.post('/api/uploads/init',{data:{filename:'混合验收.png',size:pixel.length,sha256:createHash('sha256').update(pixel).digest('hex')}})).json()
 await page.request.put('/api/uploads/'+upload.id,{data:pixel,headers:{'Upload-Offset':'0'}});await page.request.post('/api/uploads/'+upload.id+'/complete')
 const response=await page.request.post('/api/orders',{data:{upload_id:upload.id,name:'混合验收',template_ids:sets.map(s=>s.id),sticker_ids:stickers.map(s=>s.id),print_settings:{},client_token:'mixed-e2e'}})
 expect(response.ok(),await response.text()).toBeTruthy();const order=await response.json()
 expect(order.generation_count).toBe(2);expect(order.export_count).toBe(4)
 await expect.poll(async()=>(await(await page.request.get('/api/orders/'+order.id)).json()).download_ready,{timeout:60000}).toBe(true)
 const detail=await(await page.request.get('/api/orders/'+order.id)).json()
 expect(detail.export_entries).toHaveLength(4)
 expect(detail.items).toHaveLength(2)
 const paths=detail.artifacts.map((a:{path:string})=>a.path)
 expect(paths).toContain('混合验收_MIX-one_1.png');expect(paths).toContain('混合验收_MIX-one_3.png');expect(paths).toContain('混合验收_MIX-two_1.png')
})

test('unavailable legacy draft selections can be removed and replaced',async({page})=>{
 await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})
 const user=await(await page.request.get('/api/auth/me')).json()
 // Seed before mounting the app so its initial empty-draft persistence cannot overwrite the fixture.
 await page.goto('/api/health')
 await page.evaluate(async(id)=>{
  const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('avatar-stickers-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})
  await new Promise<void>((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put([{id:'legacy-missing',name:'旧草稿',file:new File(['x'],'legacy.png',{type:'image/png'}),template_ids:['removed-template'],sticker_ids:['removed-sticker'],print_settings:{paper_width_mm:210,paper_height_mm:297,long_edge_mm:85,margin_mm:10,gap_mm:10,dpi:300,brightness:false,color_balance:false},client_token:'legacy-missing'}],'drafts:'+id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()
 },user.id)
 await page.goto('/')
 await page.getByRole('button',{name:'批量选择模板'}).click()
 const dialog=page.getByRole('dialog')
 await dialog.getByRole('button',{name:'移除不可用模板 removed-template'}).click()
 await dialog.getByRole('button',{name:'移除不可用贴纸 removed-sticker'}).click()
 await expect(dialog.getByRole('button',{name:/移除不可用/})).toHaveCount(0)
 await dialog.getByLabel('搜索模板套装').fill('MIX-A');await dialog.locator('.template-option').click()
 await dialog.getByRole('button',{name:'应用到 1 个订单'}).click()
 await expect(page.locator('.submit-bar')).toContainText('预计生成 1 张 · 导出 1 张')
})
