import {uploadStickers,chooseStickers} from './library-fixtures'
import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {join} from 'node:path'
import {tmpdir} from 'node:os'

test('delete account preserves public library, requires username and revokes access',async({page,browser})=>{
  const setup=await page.request.post('/api/auth/setup',{data:{username:'deleteadmin',password:'delete-test-password',display_name:'删除验收管理员'}})
  await page.request.post('/api/auth/login',{data:setup.ok()?{username:'deleteadmin',password:'delete-test-password'}:{username:'testadmin',password:'local-test-password'}})
  const created=await(await page.request.post('/api/admin/users',{data:{username:'deletemember',display_name:'删除验收成员'}})).json()
  await page.request.patch('/api/admin/users/'+created.user.id+'/library-permission',{data:{can_edit_library:true}})
  const context=await browser.newContext({baseURL:`http://127.0.0.1:${process.env.STUDIO_E2E_FRONTEND_PORT||'5174'}`})
  try {
    const member=await context.newPage()
    await member.request.post('/api/auth/login',{data:{username:'deletemember',password:created.temporary_password}})
    const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
    const assets=await uploadStickers(member.request,Array.from({length:12},(_,i)=>({name:`delete-${i}.png`,mimeType:'image/png',buffer:pixel})))
    await member.goto('/')
    await member.getByRole('navigation').getByRole('button',{name:'模板库',exact:true}).click()
    await member.getByRole('button',{name:'新建套装',exact:true}).first().click()
    const edit=member.getByRole('dialog')
    await edit.getByLabel('套装编号').fill('DELETE-QA')
    await edit.getByLabel('套装名称').fill('保留公共套装')
    await chooseStickers(edit,assets.map(s=>s.code))
    await edit.getByRole('button',{name:'保存套装',exact:true}).click()
    await expect(edit).toHaveCount(0)
    const personal=(await(await member.request.get('/api/templates')).json()).find((t:{code:string})=>t.code==='DELETE-QA')
    expect((await member.request.get(personal.images[0].url+'/preview')).ok()).toBeTruthy()
    await page.goto('/')
    await page.getByRole('navigation').getByRole('button',{name:'账户管理',exact:true}).click()
    await page.getByRole('textbox',{name:'搜索账号'}).fill('deletemember')
    await page.getByRole('button',{name:'删除账号',exact:true}).click()
    const dialog=page.getByRole('dialog',{name:'删除成员账号',exact:true})
    await expect(dialog.getByText('0 套历史个人模板')).toBeVisible()
    await expect(dialog.getByRole('button',{name:'确认删除账号',exact:true})).toBeDisabled()
    await dialog.getByLabel('输入用户名以确认').fill('wrong')
    await expect(dialog.getByRole('button',{name:'确认删除账号',exact:true})).toBeDisabled()
    await page.keyboard.press('Escape')
    expect((await member.request.get('/api/auth/me')).ok()).toBeTruthy()
    await expect(page.getByRole('button',{name:'删除账号',exact:true})).toBeFocused()
    await page.getByRole('button',{name:'删除账号',exact:true}).click()
    await dialog.getByLabel('输入用户名以确认').fill('deletemember')
    await page.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','delete-account.png'),animations:'disabled'})
    await page.setViewportSize({width:390,height:844})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
    await page.screenshot({path:join(tmpdir(),'avatar-studio-fal-qa','delete-account-mobile.png'),animations:'disabled'})
    await dialog.getByRole('button',{name:'确认删除账号',exact:true}).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.locator('.accounts-table tbody tr')).toHaveCount(0)
    expect((await member.request.get('/api/auth/me')).status()).toBe(401)
    expect((await page.request.get(personal.images[0].url+'/preview')).status()).toBe(200)
    expect((await (await page.request.get('/api/templates')).json()).some((t:{id:string})=>t.id===personal.id)).toBeTruthy()
  } finally {await context.close()}
})
