import { test, expect } from '@playwright/test'
import { mkdirSync, readFileSync } from 'node:fs'
import { createCustomer,generateCustomer,staffLogin,submitCustomer,uploadAvatar } from './customer-fixtures'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

test('personal and admin statistics scopes, filters, charts and responsive layout', async ({page})=>{
  const errors:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  await staffLogin(page.request)
  const beforeStats=await(await page.request.get('/api/statistics?days=0')).json()
  const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
  const form=new FormData()
  for(let i=0;i<12;i++)form.append('files',new Blob([new Uint8Array(pixel)],{type:'image/png'}),`stats-${i}.png`)
  const stickers=await (await page.request.post('/api/stickers',{multipart:form})).json()
  const template=await (await page.request.post('/api/templates',{data:{code:'STAT01',name:'统计测试套装',category:'boy',sticker_ids:stickers.map((s:{id:string})=>s.id)}})).json()
  expect(template.id).toBeTruthy()
  const order=await createCustomer(page.request,{generation_limit:12,final_count:12})
  const generated=await generateCustomer(page.request,order,[{upload_id:await uploadAvatar(page.request,'统计样本.png'),template_ids:[template.id],sticker_ids:[]}])
  expect(generated.slots).toHaveLength(12)
  await submitCustomer(page.request,generated)
  const afterStats=await(await page.request.get('/api/statistics?days=0')).json()
  expect(afterStats.summary).toMatchObject({orders:beforeStats.summary.orders+1,images:beforeStats.summary.images+12,completed:beforeStats.summary.completed+12,ready_orders:beforeStats.summary.ready_orders+1})
  expect(afterStats.order_statuses.submitted).toBe(beforeStats.order_statuses.submitted+1)
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
  await expect(page.getByRole('heading',{name:'统计',exact:true,level:1})).toBeVisible()
  await expect(page.locator('.statistics-card')).toHaveCount(6)
  await page.getByLabel('统计时间范围').selectOption('0')
  await expect(page.getByText('全部订单模式下，图表展示最近 30 个自然日。')).toBeVisible()
  await page.locator('.statistics-trend').getByRole('button',{name:'图片',exact:true}).click()
  await expect(page.getByRole('img',{name:/计划图片提交趋势/})).toBeVisible()
  await page.getByLabel('搜索统计模板').fill('definitely-no-such-set')
  await expect(page.getByRole('heading',{name:'没有匹配的套装'})).toBeVisible()
  await page.getByLabel('搜索统计模板').clear()
  await expect(page.getByRole('heading',{name:'成员制作情况'})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'全站统计',exact:true}).click()
  await expect(page.getByRole('heading',{name:'成员制作情况'})).toBeVisible()
  const globalData=await (await page.request.get('/api/admin/statistics')).json()
  await expect(page.locator('.statistics-card').first().locator('strong')).toHaveText(globalData.summary.orders.toLocaleString('zh-CN'))
  await page.getByLabel('搜索统计成员').fill('no-such-member')
  await expect(page.getByRole('heading',{name:'没有匹配的成员记录'})).toBeVisible()
  await page.getByLabel('搜索统计成员').clear()
  const folder=join(tmpdir(),'avatar-studio-fal-qa');mkdirSync(folder,{recursive:true})
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:join(folder,'statistics-admin.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect.poll(()=>page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:join(folder,'statistics-mobile.png'),fullPage:true})
  const invite=(await (await page.request.post('/api/admin/invites')).json()).code
  await page.request.post('/api/auth/logout')
  expect((await page.request.post('/api/auth/register',{data:{username:'statsmember',password:'stats-member-password',display_name:'统计测试成员',invite}})).ok()).toBeTruthy()
  expect((await page.request.get('/api/admin/statistics')).status()).toBe(403)
  await page.setViewportSize({width:1440,height:1000})
  await page.reload()
  await expect(page.getByRole('navigation').getByRole('button',{name:'全站统计',exact:true})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
  await expect(page.locator('.statistics-card').first().locator('strong')).toHaveText('0')
  await expect(page.getByRole('heading',{name:'这个时间范围内还没有订单'})).toBeVisible()
  await page.screenshot({path:join(folder,'statistics-personal-empty.png'),fullPage:true})
  await page.route('**/api/statistics?*',route=>route.fulfill({status:503,json:{detail:'统计服务暂不可用'}}))
  await page.getByRole('button',{name:'刷新统计'}).click()
  await expect(page.getByRole('alert')).toContainText('统计服务暂不可用')
  await page.unroute('**/api/statistics?*')
  await page.getByRole('button',{name:'重新加载'}).click()
  await expect(page.locator('.statistics-card')).toHaveCount(6)
  expect(errors).toEqual([])
})
