import { test, expect } from '@playwright/test'
import { mkdirSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'
import { tmpdir } from 'node:os'

test('personal and admin statistics scopes, filters, charts and responsive layout', async ({page})=>{
  const errors:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  const status=await (await page.request.get('/api/auth/status')).json()
  if(status.needs_setup)await page.request.post('/api/auth/setup',{data:{username:'testadmin',password:'local-test-password',display_name:'联调管理员'}})
  else expect((await page.request.post('/api/auth/login',{data:{username:'testadmin',password:'local-test-password'}})).ok()).toBeTruthy()
  const pixel=readFileSync(new URL('./fixtures/portrait.png',import.meta.url))
  const form=new FormData()
  form.set('code','STAT01');form.set('name','统计测试套装');form.set('category','男孩')
  for(let i=0;i<12;i++)form.append('files',new Blob([new Uint8Array(pixel)],{type:'image/png'}),`stats-${i}.png`)
  const template=await (await page.request.post('/api/templates',{multipart:form})).json()
  expect(template.id).toBeTruthy()
  const upload=await (await page.request.post('/api/uploads/init',{data:{filename:'统计样本.png',size:pixel.length,sha256:createHash('sha256').update(pixel).digest('hex')}})).json()
  expect((await page.request.put('/api/uploads/'+upload.id,{data:pixel,headers:{'Upload-Offset':'0'}})).ok()).toBeTruthy()
  expect((await page.request.post('/api/uploads/'+upload.id+'/complete')).ok()).toBeTruthy()
  const order=await (await page.request.post('/api/orders',{data:{upload_id:upload.id,name:'统计样本',template_ids:[template.id],print_settings:{},client_token:'stats-order'}})).json()
  expect(order.id).toBeTruthy()
  await expect.poll(async()=> (await (await page.request.get('/api/orders/'+order.id)).json()).download_ready,{timeout:30000}).toBeTruthy()
  await page.goto('/')
  await page.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
  await expect(page.getByRole('heading',{name:'统计',exact:true,level:1})).toBeVisible()
  await expect(page.locator('.statistics-card')).toHaveCount(6)
  await page.getByLabel('统计时间范围').selectOption('0')
  await expect(page.getByText('全部订单模式下，图表展示最近 30 个自然日。')).toBeVisible()
  await page.locator('.statistics-trend').getByRole('button',{name:'图片',exact:true}).click()
  await expect(page.getByRole('img',{name:/计划图片提交趋势/})).toBeVisible()
  await page.getByLabel('搜索统计模板').fill('definitely-no-such-set')
  await expect(page.getByRole('heading',{name:'没有匹配的套装'})).toBeVisible()
  await page.getByLabel('搜索统计模板').clear()
  await expect(page.getByRole('heading',{name:'成员制作情况'})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'全站统计',exact:true}).click()
  await expect(page.getByRole('heading',{name:'成员制作情况'})).toBeVisible()
  const globalData=await (await page.request.get('/api/admin/statistics')).json()
  await expect(page.locator('.statistics-card').first().locator('strong')).toHaveText(globalData.summary.orders.toLocaleString('zh-CN'))
  await page.getByLabel('搜索统计成员').fill('no-such-member')
  await expect(page.getByRole('heading',{name:'没有匹配的成员记录'})).toBeVisible()
  await page.getByLabel('搜索统计成员').clear()
  await expect(page.getByRole('rowheader',{name:'STAT01',exact:true})).toBeVisible()
  const folder=join(tmpdir(),'avatar-studio-fal-qa');mkdirSync(folder,{recursive:true})
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:join(folder,'statistics-admin.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect.poll(()=>page.locator('.sidebar').evaluate(element=>element.getBoundingClientRect().right)).toBeLessThanOrEqual(0)
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy()
  await page.screenshot({path:join(folder,'statistics-mobile.png'),fullPage:true})
  const invite=(await (await page.request.post('/api/admin/invites')).json()).code
  await page.request.post('/api/auth/logout')
  expect((await page.request.post('/api/auth/register',{data:{username:'statsmember',password:'stats-member-password',display_name:'统计测试成员',invite}})).ok()).toBeTruthy()
  expect((await page.request.get('/api/admin/statistics')).status()).toBe(403)
  await page.setViewportSize({width:1440,height:1000})
  await page.reload()
  await expect(page.getByRole('navigation').getByRole('button',{name:'全站统计',exact:true})).toHaveCount(0)
  await page.getByRole('navigation').getByRole('button',{name:'统计',exact:true}).click()
  await expect(page.locator('.statistics-card').first().locator('strong')).toHaveText('0')
  await expect(page.getByRole('heading',{name:'这个时间范围内还没有订单'})).toBeVisible()
  await page.screenshot({path:join(folder,'statistics-personal-empty.png'),fullPage:true})
  await page.route('**/api/statistics?*',route=>route.fulfill({status:503,json:{detail:'统计服务暂不可用'}}))
  await page.getByRole('button',{name:'刷新统计'}).click()
  await expect(page.getByRole('alert')).toContainText('统计服务暂不可用')
  await page.unroute('**/api/statistics?*')
  await page.getByRole('button',{name:'重新加载'}).click()
  await expect(page.locator('.statistics-card')).toHaveCount(6)
  expect(errors).toEqual([])
})
